import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'am' | 'om' | 'ti';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.brand': 'Abeni Express',
    'nav.browse': 'Browse Products',
    'nav.request': 'Request Item',
    'nav.support': 'Support',
    'nav.admin': 'Admin Panel',
    'nav.reseller': 'Reseller Dashboard',
    'nav.signOut': 'Sign Out',
    'nav.signIn': 'Sign In',
    'nav.account': 'Account',
    'nav.cart': 'Cart',
    'nav.services': 'Services',
    'nav.seller': 'Seller Dashboard',
    'nav.driver': 'Driver Dashboard',
    
    // Language selector
    'lang.select': 'Language',
    'lang.en': 'English',
    'lang.am': 'አማርኛ',
    
    // Home page
    'home.hero.title': 'Ethiopia\'s Independent Marketplace',
    'home.hero.subtitle': 'Shop verified products and services from local sellers, paid in Ethiopian Birr, delivered by our driver network across Ethiopia.',
    'home.hero.browse': 'Browse Products',
    'home.hero.request': 'Request Custom Item',
    'home.features.title': 'Why Shop With Us?',
    'home.features.delivery': 'Fast Delivery',
    'home.features.deliveryDesc': 'Quick delivery across Ethiopia',
    'home.features.payment': 'Local Payment',
    'home.features.paymentDesc': 'Pay with CBE or Telebirr',
    'home.features.support': '24/7 Support',
    'home.features.supportDesc': 'Customer support in Amharic & English',
    'home.features.secure': 'Secure Shopping',
    'home.features.secureDesc': 'Safe and secure transactions',
    'home.reseller.title': 'Become a Reseller',
    'home.reseller.subtitle': 'Start your own store and earn profits',
    'home.reseller.apply': 'Become a Reseller',
    'home.seller.title': 'Join Our Platform',
    'home.seller.subtitle': 'Become a seller or driver and start earning',
    'home.seller.become': 'Become a Reseller',
    'home.seller.apply': 'Become a Reseller',
    'home.driver.become': 'Become a Driver',
    'home.driver.apply': 'Become a Driver',
    'home.services.browse': 'Browse Services',
    
    // Products page
    'products.title': 'Browse Products',
    'products.subtitle': 'Curated products from independent local sellers',
    'products.search': 'Search products...',
    'products.showing': 'Showing',
    'products.of': 'of',
    'products.products': 'products',
    'products.noProducts': 'No products available yet. Check back soon!',
    'products.noMatch': 'No products found matching your filters',
    'products.clearFilters': 'Clear Filters',
    'products.freeShipping': 'Free Shipping',
    'products.hotDeal': 'Hot Deal',
    'products.addToCart': 'Add to Cart',
    'products.buyNow': 'Buy Now',
    'products.cart': 'Cart',
    
    // Filters
    'filters.title': 'Filters',
    'filters.categories': 'Categories',
    'filters.priceRange': 'Price Range',
    'filters.freeShipping': 'Free Shipping Only',
    'filters.reset': 'Reset Filters',
    'filters.electronics': 'Electronics',
    'filters.fashion': 'Fashion',
    'filters.home': 'Home',
    'filters.beauty': 'Beauty',
    'filters.sports': 'Sports',
    'filters.toys': 'Toys',
    'filters.automotive': 'Automotive',
    'filters.other': 'Other',
    
    // Cart page
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.browseProducts': 'Browse Products',
    'cart.items': 'Cart Items',
    'cart.checkout': 'Checkout',
    'cart.shippingAddress': 'Shipping Address',
    'cart.city': 'City',
    'cart.phone': 'Phone',
    'cart.paymentMethod': 'Payment Method',
    'cart.selectPayment': 'Select payment method',
    'cart.cbe': 'CBE (Commercial Bank of Ethiopia)',
    'cart.telebirr': 'Telebirr',
    'cart.paymentInstructions': 'Payment Instructions:',
    'cart.transferAmount': 'Transfer the total amount to:',
    'cart.paymentProof': 'Payment Proof (Optional)',
    'cart.uploadScreenshot': 'Upload a screenshot of your payment confirmation',
    'cart.total': 'Total:',
    'cart.placeOrder': 'Place Order',
    'cart.fillShipping': 'Please fill in all shipping information',
    'cart.selectPaymentMethod': 'Please select a payment method',
    'cart.emptyCart': 'Your cart is empty',
    'cart.orderSuccess': 'Order placed successfully!',
    'cart.orderFailed': 'Failed to place order',
    'cart.itemRemoved': 'Item removed from cart',
    'cart.via': 'via',
    
    // Store page
    'store.loading': 'Loading store...',
    'store.notFound': 'Store Not Found',
    'store.notFoundDesc': 'This store does not exist',
    'store.contact': 'Contact',
    'store.searchProducts': 'Search products...',
    'store.noProducts': 'No products available',
    'store.noProductsFound': 'No products found',
    'store.addedToCart': 'Added to Cart',
    'store.addedToCartDesc': 'added to cart',
    'store.report': 'Report Store',
    'store.updateImage': 'Update Image',
    'store.uploading': 'Uploading...',
    'store.code': 'Code',
    
    // Auth page
    'auth.welcome': 'Welcome',
    'auth.description': 'Sign in to your account or create a new one',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.signingIn': 'Signing in...',
    'auth.creatingAccount': 'Creating account...',
    'auth.createAccount': 'Create Account',
    'auth.accountCreated': 'Account created! Please check your email to verify your account before signing in.',
    'auth.signedIn': 'Signed in successfully!',
    'auth.verifyEmail': 'Please verify your email before signing in. Check your inbox for the verification link.',
    
    // Account page
    'account.title': 'My Account',
    'account.yourIds': 'Your IDs',
    'account.uid': 'UID',
    'account.id': 'ID',
    'account.copy': 'Copy',
    'account.quoteRequests': 'Quote Requests',
    'account.orders': 'Orders',
    'account.refunds': 'Refunds',
    'account.noQuotes': 'No quote requests yet. Request an item to get started!',
    'account.noOrders': 'No orders yet. Start shopping to place your first order!',
    'account.noRefunds': 'No refund requests yet.',
    'account.quantity': 'Quantity',
    'account.requestedOn': 'Requested on',
    'account.items': 'Items',
    'account.total': 'Total',
    'account.shippingDetails': 'Shipping Details',
    'account.trackingInfo': 'Tracking Information',
    'account.trackPackage': 'Track your package using this number',
    'account.paymentConfirmed': 'Payment Confirmed',
    'account.orderPreparing': "Your order is being prepared. You'll receive a tracking number soon!",
    'account.requestRefund': 'Request Refund',
    'account.refundReason': 'Reason for Refund',
    'account.submitRefund': 'Submit Refund Request',
    'account.placedOn': 'Placed on',
    'account.updated': 'Updated',
    'account.order': 'Order',
    
    // Support page
    'support.title': 'Customer Support',
    'support.subtitle': "We're here to help you",
    'support.submitTicket': 'Submit a Support Ticket',
    'support.yourUserId': 'Your User ID',
    'support.userIdNote': "This is automatically filled when you're signed in",
    'support.category': 'Category',
    'support.selectCategory': 'Select a category',
    'support.subject': 'Subject',
    'support.subjectPlaceholder': 'Brief description of your issue',
    'support.message': 'Message',
    'support.messagePlaceholder': 'Please provide details about your issue...',
    'support.submit': 'Submit Ticket',
    'support.submitting': 'Submitting...',
    'support.aiSuggestion': 'AI-Suggested Solution',
    'support.aiNote': 'This is an automated suggestion. Our support team will review your ticket and provide additional assistance if needed.',
    'support.myTickets': 'My Support Tickets',
    'support.originalMessage': 'Original Message:',
    'support.supportTeam': 'Support Team',
    'support.you': 'You',
    'support.typeReply': 'Type your reply...',
    'support.ticketSubmitted': 'Ticket submitted',
    'support.ticketSubmittedDesc': 'Our support team will respond soon',
    'support.replySent': 'Reply sent',
    'support.replySentDesc': 'Your message has been sent to support',
    'support.signInRequired': 'Please sign in',
    'support.signInRequiredDesc': 'You need to be signed in to submit a support ticket',
    'support.missingInfo': 'Missing information',
    'support.missingInfoDesc': 'Please fill in all fields',
    'support.error': 'Error',
    'support.errorDesc': 'Failed to submit ticket. Please try again.',
    'support.replyError': 'Failed to send reply',
    
    // Reseller Dashboard
    'reseller.title': 'Reseller Dashboard',
    'reseller.createStore': 'Create Your Store',
    'reseller.createStoreDesc': 'You need to create a store before you can start selling.',
    'reseller.createStoreBtn': 'Create Store',
    'reseller.yourIds': 'Your IDs',
    'reseller.uid': 'UID',
    'reseller.id': 'ID',
    'reseller.copy': 'Copy',
    'reseller.storeLink': 'Your Store Link',
    'reseller.open': 'Open',
    'reseller.totalOrders': 'Total Orders',
    'reseller.pendingOrders': 'Pending Orders',
    'reseller.products': 'Products',
    'reseller.currentBalance': 'Current Balance',
    'reseller.totalEarned': 'Total Earned',
    'reseller.manageProducts': 'Manage Products',
    'reseller.orders': 'Orders',
    'reseller.viewOrders': 'View Orders',
    'reseller.viewAllOrders': 'View All Orders',
    'reseller.wallet': 'Wallet',
    'reseller.walletWithdrawals': 'Wallet & Withdrawals',
    'reseller.manageWallet': 'Manage Wallet',
    'reseller.storeSettings': 'Store Settings',
    'reseller.editStoreSettings': 'Edit Store Settings',
    'reseller.accessDenied': 'Access Denied',
    'reseller.accessDeniedDesc': 'You need reseller access to view this page',
    
    // Reseller Wallet
    'wallet.title': 'Wallet & Withdrawals',
    'wallet.currentBalance': 'Current Balance',
    'wallet.totalEarned': 'Total Earned',
    'wallet.requestWithdrawal': 'Request Withdrawal',
    'wallet.amount': 'Amount (ETB)',
    'wallet.paymentMethod': 'Payment Method',
    'wallet.telebirr': 'Telebirr',
    'wallet.cbe': 'CBE (Commercial Bank of Ethiopia)',
    'wallet.phoneNumber': 'Phone Number',
    'wallet.accountHolderName': 'Account Holder Name',
    'wallet.accountNumber': 'Account Number',
    'wallet.submitRequest': 'Submit Request',
    'wallet.withdrawalHistory': 'Withdrawal History',
    'wallet.noWithdrawals': 'No withdrawal requests yet',
    'wallet.invalidAmount': 'Please enter a valid amount',
    'wallet.insufficientBalance': 'Insufficient balance',
    'wallet.requestSubmitted': 'Withdrawal request submitted',
    
    // Reseller Setup
    'setup.title': 'Store Setup',
    'setup.createTitle': 'Create Your Store',
    'setup.editTitle': 'Edit Store Settings',
    'setup.storeName': 'Store Name',
    'setup.storeSlug': 'Store URL Slug',
    'setup.storeUrlPreview': 'Your store will be at:',
    'setup.contactEmail': 'Contact Email',
    'setup.contactPhone': 'Contact Phone',
    'setup.saving': 'Saving...',
    'setup.create': 'Create Store',
    'setup.update': 'Update Store',
    'setup.storeCreated': 'Store created successfully',
    'setup.storeUpdated': 'Store updated successfully',
    
    // Refund categories
    'refund.wrongItem': 'Wrong item received',
    'refund.damaged': 'Item damaged',
    'refund.notAsDescribed': 'Item not as described',
    'refund.noLongerNeed': 'No longer need the item',
    'refund.other': 'Other reason',
    'refund.status.pending': 'Pending',
    'refund.status.approved': 'Approved',
    'refund.status.rejected': 'Rejected',
    'refund.status.processed': 'Processed',
    
    // Apply Reseller
    'apply.title': 'Apply to Become a Reseller',
    'apply.subtitle': 'Fill in your details to apply as a reseller on our platform',
    'apply.signInRequired': 'Please sign in',
    'apply.signInDesc': 'You need to be signed in to apply as a reseller',
    'apply.personalInfo': 'Personal Information',
    'apply.fullName': 'Full Name',
    'apply.fullNamePlaceholder': 'Enter your full name',
    'apply.email': 'Email Address',
    'apply.emailPlaceholder': 'Enter your email address',
    'apply.uid': 'UID (National ID)',
    'apply.uidPlaceholder': 'Enter your national ID number',
    'apply.age': 'Age',
    'apply.agePlaceholder': 'Enter your age',
    'apply.phone': 'Phone Number',
    'apply.phonePlaceholder': 'Enter your phone number (09XXXXXXXX)',
    'apply.idVerification': 'ID Verification',
    'apply.idFront': 'ID Front Photo',
    'apply.idFrontDesc': 'Take a photo of the front of your ID',
    'apply.idBack': 'ID Back Photo',
    'apply.idBackDesc': 'Take a photo of the back of your ID',
    'apply.faceVerification': 'Face Verification',
    'apply.invalidEmail': 'Invalid Email',
    'apply.invalidEmailDesc': 'Please enter a valid email address',
    'apply.invalidPhone': 'Invalid Phone',
    'apply.invalidPhoneDesc': 'Please enter a valid Ethiopian phone number',
    'apply.invalidAge': 'Invalid Age',
    'apply.invalidAgeDesc': 'You must be at least 18 years old',
    'apply.missingInfo': 'Missing Information',
    'apply.missingInfoDesc': 'Please fill in all fields and upload required photos',
    'apply.duplicateAccount': 'Duplicate Account Detected',
    'apply.duplicateAccountDesc': 'You have already created another reseller account. Only one account per person is allowed.',
    'apply.submitted': 'Application Submitted',
    'apply.submittedDesc': 'Your reseller application has been submitted for review',
    'apply.submitError': 'Failed to submit application',
    'apply.submitting': 'Submitting...',
    'apply.submit': 'Submit Application',
    'apply.yourApplication': 'Your Reseller Application',
    'apply.status': 'Status',
    'apply.submittedOn': 'Submitted',
    'apply.adminNotes': 'Admin Notes',
    'apply.setupStore': 'Setup Your Store',
    
    // Face Authentication
    'face.title': 'Face Verification',
    'face.description': 'Complete the following challenges to verify your identity',
    'face.lookCenter': 'Look at the camera',
    'face.turnLeft': 'Turn your head left',
    'face.turnRight': 'Turn your head right',
    'face.blinkEyes': 'Blink your eyes',
    'face.complete': 'Verification complete!',
    'face.hold': 'Hold still...',
    'face.verify': 'Verify',
    'face.required': 'Face Verification Required',
    'face.requiredDesc': 'Please complete face verification to continue',
    'face.successTitle': 'Face Verified',
    'face.successDesc': 'Your face has been verified successfully',
    'face.whyNeeded': 'Why is face verification needed?',
    'face.whyNeededDesc': 'Face verification helps prevent multiple accounts and ensures the security of our platform.',
    'face.verified': 'Face Verified',
    'face.startVerification': 'Start Face Verification',
    
    // Banned User
    'banned.title': 'Account Banned',
    'banned.message': 'Your account has been banned from accessing this platform.',
    'banned.reason': 'Reason:',
    'banned.contactSupport': 'If you believe this is a mistake, please contact our support team.',
    'banned.contactButton': 'Contact Customer Support',
    
    // Notifications
    'notification.resellerApproved': 'Reseller Application Approved',
    'notification.resellerApprovedDesc': 'Your reseller application has been approved! You can now set up your store.',
    'notification.resellerRejected': 'Reseller Application Rejected',
    'notification.resellerRejectedDesc': 'Your reseller application has been rejected.',
    'notification.newNotification': 'New Notification',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.etb': 'ETB',
  },
  am: {
    // Navbar
    'nav.brand': 'አቤኒ ኤክስፕረስ',
    'nav.browse': 'ምርቶችን ይመልከቱ',
    'nav.request': 'ዕቃ ይጠይቁ',
    'nav.support': 'ድጋፍ',
    'nav.admin': 'አስተዳዳሪ ፓነል',
    'nav.reseller': 'የሻጭ ዳሽቦርድ',
    'nav.signOut': 'ውጣ',
    'nav.signIn': 'ግባ',
    'nav.account': 'መለያ',
    'nav.cart': 'ጋሪ',
    'nav.services': 'አገልግሎቶች',
    'nav.seller': 'የሻጭ ዳሽቦርድ',
    'nav.driver': 'የሾፌር ዳሽቦርድ',
    
    // Language selector
    'lang.select': 'ቋንቋ',
    'lang.en': 'English',
    'lang.am': 'አማርኛ',
    
    // Home page
    'home.hero.title': 'የኢትዮጵያ ራሱን የቻለ ገበያ',
    'home.hero.subtitle': 'ከአካባቢ ሻጮች የተረጋገጡ ምርቶችንና አገልግሎቶችን በኢትዮጵያ ብር ይግዙ — በሾፌሮቻችን አማካኝነት ወደ እርስዎ ይደርሳል።',
    'home.hero.browse': 'ምርቶችን ይመልከቱ',
    'home.hero.request': 'ዕቃ ይጠይቁ',
    'home.features.title': 'ለምን ከኛ ይገዙ?',
    'home.features.delivery': 'ፈጣን ማድረስ',
    'home.features.deliveryDesc': 'በኢትዮጵያ ውስጥ ፈጣን ማድረስ',
    'home.features.payment': 'የአገር ውስጥ ክፍያ',
    'home.features.paymentDesc': 'በCBE ወይም ቴሌብር ይክፈሉ',
    'home.features.support': '24/7 ድጋፍ',
    'home.features.supportDesc': 'በአማርኛ እና በእንግሊዝኛ የደንበኛ ድጋፍ',
    'home.features.secure': 'ደህንነቱ የተጠበቀ ግዢ',
    'home.features.secureDesc': 'ደህንነቱ የተጠበቀ ግብይቶች',
    'home.reseller.title': 'ሻጭ ይሁኑ',
    'home.reseller.subtitle': 'የራስዎን መደብር ይክፈቱ እና ትርፍ ያግኙ',
    'home.reseller.apply': 'ሻጭ ይሁኑ',
    'home.seller.title': 'መድረካችንን ይቀላቀሉ',
    'home.seller.subtitle': 'ሻጭ ወይም ሾፌር ይሁኑ እና ገቢ ማግኘት ይጀምሩ',
    'home.seller.become': 'ሻጭ ይሁኑ',
    'home.seller.apply': 'ሻጭ ይሁኑ',
    'home.driver.become': 'ሾፌር ይሁኑ',
    'home.driver.apply': 'ሾፌር ይሁኑ',
    'home.services.browse': 'አገልግሎቶችን ይመልከቱ',
    
    // Products page
    'products.title': 'ምርቶችን ይመልከቱ',
    'products.subtitle': 'ከአካባቢ ሻጮች የተመረጡ ምርቶች',
    'products.search': 'ምርቶችን ይፈልጉ...',
    'products.showing': 'እያሳየ',
    'products.of': 'ከ',
    'products.products': 'ምርቶች',
    'products.noProducts': 'ገና ምርቶች የሉም። በቅርቡ ይመልከቱ!',
    'products.noMatch': 'ከማጣሪያዎ ጋር የሚዛመድ ምርት አልተገኘም',
    'products.clearFilters': 'ማጣሪያዎችን ያጽዱ',
    'products.freeShipping': 'ነፃ ማጓጓዣ',
    'products.hotDeal': 'ጥሩ ቅናሽ',
    'products.addToCart': 'ወደ ጋሪ ጨምር',
    'products.buyNow': 'አሁን ግዛ',
    'products.cart': 'ጋሪ',
    
    // Filters
    'filters.title': 'ማጣሪያዎች',
    'filters.categories': 'ምድቦች',
    'filters.priceRange': 'የዋጋ ክልል',
    'filters.freeShipping': 'ነፃ ማጓጓዣ ብቻ',
    'filters.reset': 'ማጣሪያዎችን ዳግም አስጀምር',
    'filters.electronics': 'ኤሌክትሮኒክስ',
    'filters.fashion': 'ፋሽን',
    'filters.home': 'ቤት',
    'filters.beauty': 'ውበት',
    'filters.sports': 'ስፖርት',
    'filters.toys': 'መጫወቻዎች',
    'filters.automotive': 'መኪና',
    'filters.other': 'ሌላ',
    
    // Cart page
    'cart.title': 'የግዢ ጋሪ',
    'cart.empty': 'ጋሪዎ ባዶ ነው',
    'cart.browseProducts': 'ምርቶችን ይመልከቱ',
    'cart.items': 'በጋሪ ውስጥ ያሉ ዕቃዎች',
    'cart.checkout': 'ይክፈሉ',
    'cart.shippingAddress': 'የመላኪያ አድራሻ',
    'cart.city': 'ከተማ',
    'cart.phone': 'ስልክ',
    'cart.paymentMethod': 'የክፍያ ዘዴ',
    'cart.selectPayment': 'የክፍያ ዘዴ ይምረጡ',
    'cart.cbe': 'CBE (የኢትዮጵያ ንግድ ባንክ)',
    'cart.telebirr': 'ቴሌብር',
    'cart.paymentInstructions': 'የክፍያ መመሪያ:',
    'cart.transferAmount': 'ጠቅላላ ገንዘቡን ወደዚህ ያስተላልፉ:',
    'cart.paymentProof': 'የክፍያ ማረጋገጫ (አማራጭ)',
    'cart.uploadScreenshot': 'የክፍያ ማረጋገጫ ስክሪንሾት ይስቀሉ',
    'cart.total': 'ጠቅላላ:',
    'cart.placeOrder': 'ትዕዛዝ ያስገቡ',
    'cart.fillShipping': 'እባክዎ ሁሉንም የመላኪያ መረጃ ይሙሉ',
    'cart.selectPaymentMethod': 'እባክዎ የክፍያ ዘዴ ይምረጡ',
    'cart.emptyCart': 'ጋሪዎ ባዶ ነው',
    'cart.orderSuccess': 'ትዕዛዝ በተሳካ ሁኔታ ተልኳል!',
    'cart.orderFailed': 'ትዕዛዝ መላክ አልተሳካም',
    'cart.itemRemoved': 'ዕቃ ከጋሪ ተወግዷል',
    'cart.via': 'በ',
    
    // Store page
    'store.loading': 'መደብር በመጫን ላይ...',
    'store.notFound': 'መደብር አልተገኘም',
    'store.notFoundDesc': 'ይህ መደብር የለም',
    'store.contact': 'አግኙን',
    'store.searchProducts': 'ምርቶችን ይፈልጉ...',
    'store.noProducts': 'ምርቶች የሉም',
    'store.noProductsFound': 'ምርቶች አልተገኙም',
    'store.addedToCart': 'ወደ ጋሪ ተጨምሯል',
    'store.addedToCartDesc': 'ወደ ጋሪ ተጨምሯል',
    'store.report': 'መደብር ሪፖርት አድርግ',
    'store.updateImage': 'ምስል አዘምን',
    'store.uploading': 'በመስቀል ላይ...',
    'store.code': 'ኮድ',
    
    // Auth page
    'auth.welcome': 'እንኳን ደህና መጡ',
    'auth.description': 'ወደ መለያዎ ይግቡ ወይም አዲስ ይፍጠሩ',
    'auth.signIn': 'ግባ',
    'auth.signUp': 'ተመዝገብ',
    'auth.email': 'ኢሜይል',
    'auth.password': 'የይለፍ ቃል',
    'auth.fullName': 'ሙሉ ስም',
    'auth.signingIn': 'በመግባት ላይ...',
    'auth.creatingAccount': 'መለያ በመፍጠር ላይ...',
    'auth.createAccount': 'መለያ ፍጠር',
    'auth.accountCreated': 'መለያ ተፈጠረ! እባክዎ ከመግባትዎ በፊት ኢሜይልዎን ያረጋግጡ።',
    'auth.signedIn': 'በተሳካ ሁኔታ ገብተዋል!',
    'auth.verifyEmail': 'ከመግባትዎ በፊት እባክዎ ኢሜይልዎን ያረጋግጡ።',
    
    // Account page
    'account.title': 'የኔ መለያ',
    'account.yourIds': 'የእርስዎ መታወቂያዎች',
    'account.uid': 'UID',
    'account.id': 'ID',
    'account.copy': 'ቅዳ',
    'account.quoteRequests': 'የዋጋ ጥያቄዎች',
    'account.orders': 'ትዕዛዞች',
    'account.refunds': 'ተመላሾች',
    'account.noQuotes': 'ገና የዋጋ ጥያቄዎች የሉም። ዕቃ ይጠይቁ ለመጀመር!',
    'account.noOrders': 'ገና ትዕዛዞች የሉም። ግዢ ለመጀመር ምርቶችን ይመልከቱ!',
    'account.noRefunds': 'ገና የተመላሽ ጥያቄዎች የሉም።',
    'account.quantity': 'ብዛት',
    'account.requestedOn': 'የተጠየቀበት ቀን',
    'account.items': 'ዕቃዎች',
    'account.total': 'ጠቅላላ',
    'account.shippingDetails': 'የመላኪያ ዝርዝሮች',
    'account.trackingInfo': 'የመከታተያ መረጃ',
    'account.trackPackage': 'ይህንን ቁጥር በመጠቀም ዕቃዎን ይከታተሉ',
    'account.paymentConfirmed': 'ክፍያ ተረጋግጧል',
    'account.orderPreparing': 'ትዕዛዝዎ በመዘጋጀት ላይ ነው። በቅርቡ የመከታተያ ቁጥር ይደርስዎታል!',
    'account.requestRefund': 'ተመላሽ ጠይቅ',
    'account.refundReason': 'የተመላሽ ምክንያት',
    'account.submitRefund': 'የተመላሽ ጥያቄ ላክ',
    'account.placedOn': 'የታዘዘበት ቀን',
    'account.updated': 'የተዘመነ',
    'account.order': 'ትዕዛዝ',
    
    // Support page
    'support.title': 'የደንበኛ ድጋፍ',
    'support.subtitle': 'እርስዎን ለመርዳት እዚህ ነን',
    'support.submitTicket': 'የድጋፍ ቲኬት ላክ',
    'support.yourUserId': 'የእርስዎ ተጠቃሚ መታወቂያ',
    'support.userIdNote': 'ሲገቡ ይህ በራስ ሰር ይሞላል',
    'support.category': 'ምድብ',
    'support.selectCategory': 'ምድብ ይምረጡ',
    'support.subject': 'ርዕሰ ጉዳይ',
    'support.subjectPlaceholder': 'ስለ ችግርዎ አጭር መግለጫ',
    'support.message': 'መልዕክት',
    'support.messagePlaceholder': 'እባክዎ ስለ ችግርዎ ዝርዝሮችን ያቅርቡ...',
    'support.submit': 'ቲኬት ላክ',
    'support.submitting': 'በመላክ ላይ...',
    'support.aiSuggestion': 'በ AI የተጠቆመ መፍትሄ',
    'support.aiNote': 'ይህ አውቶማቲክ ጥቆማ ነው። የድጋፍ ቡድናችን ቲኬትዎን ይገመግማል እና ተጨማሪ እርዳታ ይሰጣል።',
    'support.myTickets': 'የእኔ የድጋፍ ቲኬቶች',
    'support.originalMessage': 'የመጀመሪያ መልዕክት:',
    'support.supportTeam': 'የድጋፍ ቡድን',
    'support.you': 'እርስዎ',
    'support.typeReply': 'ምላሽዎን ይፃፉ...',
    'support.ticketSubmitted': 'ቲኬት ተልኳል',
    'support.ticketSubmittedDesc': 'የድጋፍ ቡድናችን በቅርቡ ምላሽ ይሰጣል',
    'support.replySent': 'ምላሽ ተልኳል',
    'support.replySentDesc': 'መልዕክትዎ ወደ ድጋፍ ተልኳል',
    'support.signInRequired': 'እባክዎ ይግቡ',
    'support.signInRequiredDesc': 'የድጋፍ ቲኬት ለመላክ መግባት አለብዎት',
    'support.missingInfo': 'የጎደለ መረጃ',
    'support.missingInfoDesc': 'እባክዎ ሁሉንም መስኮች ይሙሉ',
    'support.error': 'ስህተት',
    'support.errorDesc': 'ቲኬት መላክ አልተሳካም። እባክዎ እንደገና ይሞክሩ።',
    'support.replyError': 'ምላሽ መላክ አልተሳካም',
    
    // Reseller Dashboard
    'reseller.title': 'የሻጭ ዳሽቦርድ',
    'reseller.createStore': 'መደብርዎን ይፍጠሩ',
    'reseller.createStoreDesc': 'መሸጥ ከመጀመርዎ በፊት መደብር መፍጠር አለብዎት።',
    'reseller.createStoreBtn': 'መደብር ፍጠር',
    'reseller.yourIds': 'የእርስዎ መታወቂያዎች',
    'reseller.uid': 'UID',
    'reseller.id': 'ID',
    'reseller.copy': 'ቅዳ',
    'reseller.storeLink': 'የመደብር ሊንክዎ',
    'reseller.open': 'ክፈት',
    'reseller.totalOrders': 'ጠቅላላ ትዕዛዞች',
    'reseller.pendingOrders': 'በመጠባበቅ ላይ ያሉ ትዕዛዞች',
    'reseller.products': 'ምርቶች',
    'reseller.currentBalance': 'የአሁኑ ቀሪ ሂሳብ',
    'reseller.totalEarned': 'ጠቅላላ ገቢ',
    'reseller.manageProducts': 'ምርቶችን አስተዳድር',
    'reseller.orders': 'ትዕዛዞች',
    'reseller.viewOrders': 'ትዕዛዞችን ይመልከቱ',
    'reseller.viewAllOrders': 'ሁሉንም ትዕዛዞች ይመልከቱ',
    'reseller.wallet': 'ኪስ',
    'reseller.walletWithdrawals': 'ኪስ እና ማውጣት',
    'reseller.manageWallet': 'ኪስ አስተዳድር',
    'reseller.storeSettings': 'የመደብር ቅንብሮች',
    'reseller.editStoreSettings': 'የመደብር ቅንብሮችን አርትዕ',
    'reseller.accessDenied': 'መዳረሻ ተከልክሏል',
    'reseller.accessDeniedDesc': 'ይህን ገጽ ለመመልከት የሻጭ መዳረሻ ያስፈልግዎታል',
    
    // Reseller Wallet
    'wallet.title': 'ኪስ እና ማውጣት',
    'wallet.currentBalance': 'የአሁኑ ቀሪ ሂሳብ',
    'wallet.totalEarned': 'ጠቅላላ ገቢ',
    'wallet.requestWithdrawal': 'ማውጣት ጠይቅ',
    'wallet.amount': 'መጠን (ETB)',
    'wallet.paymentMethod': 'የክፍያ ዘዴ',
    'wallet.telebirr': 'ቴሌብር',
    'wallet.cbe': 'CBE (የኢትዮጵያ ንግድ ባንክ)',
    'wallet.phoneNumber': 'ስልክ ቁጥር',
    'wallet.accountHolderName': 'የመለያ ባለቤት ስም',
    'wallet.accountNumber': 'የመለያ ቁጥር',
    'wallet.submitRequest': 'ጥያቄ ላክ',
    'wallet.withdrawalHistory': 'የማውጣት ታሪክ',
    'wallet.noWithdrawals': 'ገና የማውጣት ጥያቄዎች የሉም',
    'wallet.invalidAmount': 'እባክዎ ትክክለኛ መጠን ያስገቡ',
    'wallet.insufficientBalance': 'በቂ ቀሪ ሂሳብ የለም',
    'wallet.requestSubmitted': 'የማውጣት ጥያቄ ተልኳል',
    
    // Reseller Setup
    'setup.title': 'የመደብር ማዋቀር',
    'setup.createTitle': 'መደብርዎን ይፍጠሩ',
    'setup.editTitle': 'የመደብር ቅንብሮችን አርትዕ',
    'setup.storeName': 'የመደብር ስም',
    'setup.storeSlug': 'የመደብር URL Slug',
    'setup.storeUrlPreview': 'መደብርዎ የሚገኝበት:',
    'setup.contactEmail': 'የመገኛ ኢሜይል',
    'setup.contactPhone': 'የመገኛ ስልክ',
    'setup.saving': 'በማስቀመጥ ላይ...',
    'setup.create': 'መደብር ፍጠር',
    'setup.update': 'መደብር አዘምን',
    'setup.storeCreated': 'መደብር በተሳካ ሁኔታ ተፈጠረ',
    'setup.storeUpdated': 'መደብር በተሳካ ሁኔታ ተዘመነ',
    
    // Refund categories
    'refund.wrongItem': 'የተሳሳተ ዕቃ ደረሰ',
    'refund.damaged': 'ዕቃ ተበላሽቷል',
    'refund.notAsDescribed': 'ዕቃ እንደተገለጸው አይደለም',
    'refund.noLongerNeed': 'ዕቃ ከአሁን በኋላ አያስፈልገኝም',
    'refund.other': 'ሌላ ምክንያት',
    'refund.status.pending': 'በመጠባበቅ ላይ',
    'refund.status.approved': 'ተቀባይነት አግኝቷል',
    'refund.status.rejected': 'ተቀባይነት አላገኘም',
    'refund.status.processed': 'ተሠርቷል',
    
    // Apply Reseller
    'apply.title': 'ሻጭ ለመሆን ያመልክቱ',
    'apply.subtitle': 'በእኛ መድረክ ላይ ሻጭ ለመሆን ዝርዝሮችዎን ይሙሉ',
    'apply.signInRequired': 'እባክዎ ይግቡ',
    'apply.signInDesc': 'ሻጭ ለመሆን ማመልከት መግባት አለብዎት',
    'apply.personalInfo': 'የግል መረጃ',
    'apply.fullName': 'ሙሉ ስም',
    'apply.fullNamePlaceholder': 'ሙሉ ስምዎን ያስገቡ',
    'apply.email': 'ኢሜይል አድራሻ',
    'apply.emailPlaceholder': 'ኢሜይል አድራሻዎን ያስገቡ',
    'apply.uid': 'UID (ብሔራዊ መታወቂያ)',
    'apply.uidPlaceholder': 'ብሔራዊ መታወቂያ ቁጥርዎን ያስገቡ',
    'apply.age': 'ዕድሜ',
    'apply.agePlaceholder': 'ዕድሜዎን ያስገቡ',
    'apply.phone': 'ስልክ ቁጥር',
    'apply.phonePlaceholder': 'ስልክ ቁጥርዎን ያስገቡ (09XXXXXXXX)',
    'apply.idVerification': 'የመታወቂያ ማረጋገጫ',
    'apply.idFront': 'የመታወቂያ ፊት ፎቶ',
    'apply.idFrontDesc': 'የመታወቂያዎን ፊት ለፊት ፎቶ ያንሱ',
    'apply.idBack': 'የመታወቂያ ጀርባ ፎቶ',
    'apply.idBackDesc': 'የመታወቂያዎን ጀርባ ፎቶ ያንሱ',
    'apply.faceVerification': 'የፊት ማረጋገጫ',
    'apply.invalidEmail': 'ልክ ያልሆነ ኢሜይል',
    'apply.invalidEmailDesc': 'እባክዎ ትክክለኛ ኢሜይል አድራሻ ያስገቡ',
    'apply.invalidPhone': 'ልክ ያልሆነ ስልክ',
    'apply.invalidPhoneDesc': 'እባክዎ ትክክለኛ የኢትዮጵያ ስልክ ቁጥር ያስገቡ',
    'apply.invalidAge': 'ልክ ያልሆነ ዕድሜ',
    'apply.invalidAgeDesc': 'ቢያንስ 18 ዓመት መሆን አለብዎት',
    'apply.missingInfo': 'የጎደለ መረጃ',
    'apply.missingInfoDesc': 'እባክዎ ሁሉንም መስኮች ይሙሉ እና አስፈላጊ ፎቶዎችን ይስቀሉ',
    'apply.duplicateAccount': 'ድግግሞሽ መለያ ተገኝቷል',
    'apply.duplicateAccountDesc': 'ቀደም ሲል ሌላ የሻጭ መለያ ፈጥረዋል። በአንድ ሰው አንድ መለያ ብቻ ይፈቀዳል።',
    'apply.submitted': 'ማመልከቻ ተልኳል',
    'apply.submittedDesc': 'የሻጭ ማመልከቻዎ ለግምገማ ተልኳል',
    'apply.submitError': 'ማመልከቻ መላክ አልተሳካም',
    'apply.submitting': 'በመላክ ላይ...',
    'apply.submit': 'ማመልከቻ ላክ',
    'apply.yourApplication': 'የሻጭ ማመልከቻዎ',
    'apply.status': 'ሁኔታ',
    'apply.submittedOn': 'የተላከበት',
    'apply.adminNotes': 'የአስተዳዳሪ ማስታወሻዎች',
    'apply.setupStore': 'መደብርዎን ያዋቅሩ',
    
    // Face Authentication
    'face.title': 'የፊት ማረጋገጫ',
    'face.description': 'ማንነትዎን ለማረጋገጥ የሚከተሉትን ተግዳሮቶች ያጠናቅቁ',
    'face.lookCenter': 'ወደ ካሜራው ይመልከቱ',
    'face.turnLeft': 'ራስዎን ወደ ግራ ያዙሩ',
    'face.turnRight': 'ራስዎን ወደ ቀኝ ያዙሩ',
    'face.blinkEyes': 'ዓይንዎን ያብጩ',
    'face.complete': 'ማረጋገጫ ተጠናቋል!',
    'face.hold': 'ይጠብቁ...',
    'face.verify': 'አረጋግጥ',
    'face.required': 'የፊት ማረጋገጫ ያስፈልጋል',
    'face.requiredDesc': 'እባክዎ ለመቀጠል የፊት ማረጋገጫ ያጠናቅቁ',
    'face.successTitle': 'ፊት ተረጋግጧል',
    'face.successDesc': 'ፊትዎ በተሳካ ሁኔታ ተረጋግጧል',
    'face.whyNeeded': 'የፊት ማረጋገጫ ለምን ያስፈልጋል?',
    'face.whyNeededDesc': 'የፊት ማረጋገጫ ብዙ መለያዎችን ለመከላከል እና የመድረካችንን ደህንነት ለማረጋገጥ ይረዳል።',
    'face.verified': 'ፊት ተረጋግጧል',
    'face.startVerification': 'የፊት ማረጋገጫ ጀምር',
    
    // Banned User
    'banned.title': 'መለያ ታግዷል',
    'banned.message': 'መለያዎ ይህን መድረክ ከመጠቀም ታግዷል።',
    'banned.reason': 'ምክንያት:',
    'banned.contactSupport': 'ይህ ስህተት ነው ብለው ካሰቡ፣ እባክዎ የድጋፍ ቡድናችንን ያነጋግሩ።',
    'banned.contactButton': 'የደንበኛ ድጋፍ ያግኙ',
    
    // Notifications
    'notification.resellerApproved': 'የሻጭ ማመልከቻ ተቀባይነት አግኝቷል',
    'notification.resellerApprovedDesc': 'የሻጭ ማመልከቻዎ ተቀባይነት አግኝቷል! አሁን መደብርዎን ማዋቀር ይችላሉ።',
    'notification.resellerRejected': 'የሻጭ ማመልከቻ ተቀባይነት አላገኘም',
    'notification.resellerRejectedDesc': 'የሻጭ ማመልከቻዎ ተቀባይነት አላገኘም።',
    'notification.newNotification': 'አዲስ ማሳወቂያ',
    
    // Common
    'common.loading': 'በመጫን ላይ...',
    'common.error': 'ስህተት',
    'common.success': 'ተሳክቷል',
    'common.cancel': 'ሰርዝ',
    'common.confirm': 'አረጋግጥ',
    'common.save': 'አስቀምጥ',
    'common.delete': 'ሰርዝ',
    'common.edit': 'አርትዕ',
    'common.view': 'ይመልከቱ',
    'common.back': 'ተመለስ',
    'common.next': 'ቀጣይ',
    'common.previous': 'ቀዳሚ',
    'common.etb': 'ብር',
  },
  // Afaan Oromo — partial translation; missing keys fall back to English.
  om: {
    'nav.brand': 'Abeni Express',
    'nav.browse': 'Oomishaalee Ilaali',
    'nav.request': 'Meeshaa Gaafadhu',
    'nav.support': 'Deeggarsa',
    'nav.admin': 'Paanaalii Bulchaa',
    'nav.reseller': 'Daashboordii Gurguraa',
    'nav.signOut': 'Bahi',
    'nav.signIn': 'Seeni',
    'nav.account': 'Akkaawuntii',
    'nav.cart': 'Galmee',
    'nav.services': 'Tajaajila',
    'nav.seller': 'Daashboordii Gurguraa',
    'nav.driver': 'Daashboordii Konkolaachisaa',
    'lang.select': 'Afaan',
    'lang.en': 'English',
    'lang.am': 'አማርኛ',
    'lang.om': 'Afaan Oromoo',
    'lang.ti': 'ትግርኛ',
    'home.hero.title': 'Gabaa Walaba Itoophiyaa',
    'home.hero.subtitle': 'Oomishaalee fi tajaajila mirkaneeffaman gurgurtoota naannoo irraa Birrii Itoophiyaatiin bitadhu — geejjibsiistota keenyaan mana keessanitti dhihaata.',
    'home.hero.browse': 'Oomishaalee Ilaali',
    'home.hero.request': 'Meeshaa Gaafadhu',
    'common.loading': 'Fe’amaa jira...',
    'common.error': 'Dogoggora',
    'common.success': 'Milkaa’ina',
    'common.cancel': 'Haqi',
    'common.confirm': 'Mirkaneessi',
    'common.save': 'Olkaa’i',
    'common.delete': 'Balleessi',
    'common.edit': 'Gulaali',
    'common.view': 'Ilaali',
    'common.back': 'Duubatti',
    'common.next': 'Itti aanu',
    'common.previous': 'Kan duraa',
    'common.etb': 'ETB',
  },
  // Tigrigna — partial translation; missing keys fall back to English.
  ti: {
    'nav.brand': 'ኣቤኒ ኤክስፕረስ',
    'nav.browse': 'ምህርቲ ርአ',
    'nav.request': 'ኣቕሓ ሓትት',
    'nav.support': 'ደገፍ',
    'nav.admin': 'ናይ ኣመሓዳሪ ፓነል',
    'nav.reseller': 'ናይ ሸያጢ ዳሽቦርድ',
    'nav.signOut': 'ውጻእ',
    'nav.signIn': 'እቶ',
    'nav.account': 'ሕሳብ',
    'nav.cart': 'ዓረብያ',
    'nav.services': 'ኣገልግሎታት',
    'nav.seller': 'ናይ ሸያጢ ዳሽቦርድ',
    'nav.driver': 'ናይ ዘዋሪ ዳሽቦርድ',
    'lang.select': 'ቋንቋ',
    'lang.en': 'English',
    'lang.am': 'አማርኛ',
    'lang.om': 'Afaan Oromoo',
    'lang.ti': 'ትግርኛ',
    'home.hero.title': 'ናጻ ዕዳጋ ኢትዮጵያ',
    'home.hero.subtitle': 'ካብ ናይ ከባቢ ሸየጥቲ ዝተረጋገጹ ምህርትን ኣገልግሎትን ብኢትዮጵያ ብር ግዙ — ብዘወርቲ ናባኹም ይመጽእ።',
    'home.hero.browse': 'ምህርቲ ርአ',
    'home.hero.request': 'ኣቕሓ ሓትት',
    'common.loading': 'ይጽዓን ኣሎ...',
    'common.error': 'ጌጋ',
    'common.success': 'ዕዉት',
    'common.cancel': 'ሰርዝ',
    'common.confirm': 'ኣረጋግጽ',
    'common.save': 'ኣቐምጥ',
    'common.delete': 'ሰርዝ',
    'common.edit': 'ኣርም',
    'common.view': 'ርአ',
    'common.back': 'ድሕሪት',
    'common.next': 'ቀጻሊ',
    'common.previous': 'ዝሓለፈ',
    'common.etb': 'ETB',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  // Falls back to English when the active language is missing a key, so the
  // partially-translated languages (om, ti) still render correctly.
  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
