import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'am' | 'om' | 'ti';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.brand': 'Abeni Express',
    'nav.browse': 'Browse Products',
    'nav.request': 'Request Item',
    'nav.support': 'Support',
    'nav.admin': 'Admin Panel',
    'nav.reseller': 'Seller Dashboard',
    'nav.signOut': 'Sign Out',
    'nav.signIn': 'Sign In',
    'nav.account': 'Account',
    'nav.cart': 'Cart',
    'nav.services': 'Services',
    'nav.seller': 'Seller Dashboard',
    'nav.driver': 'Driver Dashboard',
    
    // Language selector
    'lang.select': 'Language',
    'lang.en': 'English',
    'lang.am': 'አማርኛ',
    
    // Home page
    'home.hero.title': 'Ethiopia\'s Independent Marketplace',
    'home.hero.subtitle': 'Shop verified products and services from local sellers, paid in Ethiopian Birr, delivered by our driver network across Ethiopia.',
    'home.hero.browse': 'Browse Products',
    'home.hero.request': 'Request Custom Item',
    'home.features.title': 'Why Shop With Us?',
    'home.features.delivery': 'Fast Delivery',
    'home.features.deliveryDesc': 'Quick delivery across Ethiopia',
    'home.features.payment': 'Local Payment',
    'home.features.paymentDesc': 'Pay with CBE or Telebirr',
    'home.features.support': '24/7 Support',
    'home.features.supportDesc': 'Customer support in Amharic & English',
    'home.features.secure': 'Secure Shopping',
    'home.features.secureDesc': 'Safe and secure transactions',
    'home.reseller.title': 'Become a Seller',
    'home.reseller.subtitle': 'Start your own store and earn profits',
    'home.reseller.apply': 'Become a Seller',
    'home.seller.title': 'Join Our Platform',
    'home.seller.subtitle': 'Become a seller or driver and start earning',
    'home.seller.become': 'Become a Seller',
    'home.seller.apply': 'Become a Seller',
    'home.driver.become': 'Become a Driver',
    'home.driver.apply': 'Become a Driver',
    'home.services.browse': 'Browse Services',
    
    // Products page
    'products.title': 'Browse Products',
    'products.subtitle': 'Curated products from independent local sellers',
    'products.search': 'Search products...',
    'products.showing': 'Showing',
    'products.of': 'of',
    'products.products': 'products',
    'products.noProducts': 'No products available yet. Check back soon!',
    'products.noMatch': 'No products found matching your filters',
    'products.clearFilters': 'Clear Filters',
    'products.freeShipping': 'Free Shipping',
    'products.hotDeal': 'Hot Deal',
    'products.addToCart': 'Add to Cart',
    'products.buyNow': 'Buy Now',
    'products.cart': 'Cart',
    
    // Filters
    'filters.title': 'Filters',
    'filters.categories': 'Categories',
    'filters.priceRange': 'Price Range',
    'filters.freeShipping': 'Free Shipping Only',
    'filters.reset': 'Reset Filters',
    'filters.electronics': 'Electronics',
    'filters.fashion': 'Fashion',
    'filters.home': 'Home',
    'filters.beauty': 'Beauty',
    'filters.sports': 'Sports',
    'filters.toys': 'Toys',
    'filters.automotive': 'Automotive',
    'filters.other': 'Other',
    
    // Cart page
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.browseProducts': 'Browse Products',
    'cart.items': 'Cart Items',
    'cart.checkout': 'Checkout',
    'cart.shippingAddress': 'Shipping Address',
    'cart.city': 'City',
    'cart.phone': 'Phone',
    'cart.paymentMethod': 'Payment Method',
    'cart.selectPayment': 'Select payment method',
    'cart.cbe': 'CBE (Commercial Bank of Ethiopia)',
    'cart.telebirr': 'Telebirr',
    'cart.paymentInstructions': 'Payment Instructions:',
    'cart.transferAmount': 'Transfer the total amount to:',
    'cart.paymentProof': 'Payment Proof (Optional)',
    'cart.uploadScreenshot': 'Upload a screenshot of your payment confirmation',
    'cart.total': 'Total:',
    'cart.placeOrder': 'Place Order',
    'cart.fillShipping': 'Please fill in all shipping information',
    'cart.selectPaymentMethod': 'Please select a payment method',
    'cart.emptyCart': 'Your cart is empty',
    'cart.orderSuccess': 'Order placed successfully!',
    'cart.orderFailed': 'Failed to place order',
    'cart.itemRemoved': 'Item removed from cart',
    'cart.via': 'via',
    
    // Store page
    'store.loading': 'Loading store...',
    'store.notFound': 'Store Not Found',
    'store.notFoundDesc': 'This store does not exist',
    'store.contact': 'Contact',
    'store.searchProducts': 'Search products...',
    'store.noProducts': 'No products available',
    'store.noProductsFound': 'No products found',
    'store.addedToCart': 'Added to Cart',
    'store.addedToCartDesc': 'added to cart',
    'store.report': 'Report Store',
    'store.updateImage': 'Update Image',
    'store.uploading': 'Uploading...',
    'store.code': 'Code',
    
    // Auth page
    'auth.welcome': 'Welcome',
    'auth.description': 'Sign in to your account or create a new one',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.signingIn': 'Signing in...',
    'auth.creatingAccount': 'Creating account...',
    'auth.createAccount': 'Create Account',
    'auth.accountCreated': 'Account created! Please check your email to verify your account before signing in.',
    'auth.signedIn': 'Signed in successfully!',
    'auth.verifyEmail': 'Please verify your email before signing in. Check your inbox for the verification link.',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.forgotPasswordDesc': 'Enter your email and we will send you a reset link.',
    'auth.backToLogin': 'Back to Sign In',
    
    // Account page
    'account.title': 'My Account',
    'account.yourIds': 'Your IDs',
    'account.uid': 'UID',
    'account.id': 'ID',
    'account.copy': 'Copy',
    'account.quoteRequests': 'Quote Requests',
    'account.orders': 'Orders',
    'account.refunds': 'Refunds',
    'account.noQuotes': 'No quote requests yet. Request an item to get started!',
    'account.noOrders': 'No orders yet. Start shopping to place your first order!',
    'account.noRefunds': 'No refund requests yet.',
    'account.quantity': 'Quantity',
    'account.requestedOn': 'Requested on',
    'account.items': 'Items',
    'account.total': 'Total',
    'account.shippingDetails': 'Shipping Details',
    'account.trackingInfo': 'Tracking Information',
    'account.trackPackage': 'Track your package using this number',
    'account.paymentConfirmed': 'Payment Confirmed',
    'account.orderPreparing': "Your order is being prepared. You'll receive a tracking number soon!",
    'account.requestRefund': 'Request Refund',
    'account.refundReason': 'Reason for Refund',
    'account.submitRefund': 'Submit Refund Request',
    'account.placedOn': 'Placed on',
    'account.updated': 'Updated',
    'account.order': 'Order',
    
    // Support page
    'support.title': 'Customer Support',
    'support.subtitle': "We're here to help you",
    'support.submitTicket': 'Submit a Support Ticket',
    'support.yourUserId': 'Your User ID',
    'support.userIdNote': "This is automatically filled when you're signed in",
    'support.category': 'Category',
    'support.selectCategory': 'Select a category',
    'support.subject': 'Subject',
    'support.subjectPlaceholder': 'Brief description of your issue',
    'support.message': 'Message',
    'support.messagePlaceholder': 'Please provide details about your issue...',
    'support.submit': 'Submit Ticket',
    'support.submitting': 'Submitting...',
    'support.aiSuggestion': 'AI-Suggested Solution',
    'support.aiNote': 'This is an automated suggestion. Our support team will review your ticket and provide additional assistance if needed.',
    'support.myTickets': 'My Support Tickets',
    'support.originalMessage': 'Original Message:',
    'support.supportTeam': 'Support Team',
    'support.you': 'You',
    'support.typeReply': 'Type your reply...',
    'support.ticketSubmitted': 'Ticket submitted',
    'support.ticketSubmittedDesc': 'Our support team will respond soon',
    'support.replySent': 'Reply sent',
    'support.replySentDesc': 'Your message has been sent to support',
    'support.signInRequired': 'Please sign in',
    'support.signInRequiredDesc': 'You need to be signed in to submit a support ticket',
    'support.missingInfo': 'Missing information',
    'support.missingInfoDesc': 'Please fill in all fields',
    'support.error': 'Error',
    'support.errorDesc': 'Failed to submit ticket. Please try again.',
    'support.replyError': 'Failed to send reply',
    
    // Seller Dashboard
    'reseller.title': 'Seller Dashboard',
    'reseller.createStore': 'Create Your Store',
    'reseller.createStoreDesc': 'You need to create a store before you can start selling.',
    'reseller.createStoreBtn': 'Create Store',
    'reseller.yourIds': 'Your IDs',
    'reseller.uid': 'UID',
    'reseller.id': 'ID',
    'reseller.copy': 'Copy',
    'reseller.storeLink': 'Your Store Link',
    'reseller.open': 'Open',
    'reseller.totalOrders': 'Total Orders',
    'reseller.pendingOrders': 'Pending Orders',
    'reseller.products': 'Products',
    'reseller.currentBalance': 'Current Balance',
    'reseller.totalEarned': 'Total Earned',
    'reseller.manageProducts': 'Manage Products',
    'reseller.orders': 'Orders',
    'reseller.viewOrders': 'View Orders',
    'reseller.viewAllOrders': 'View All Orders',
    'reseller.wallet': 'Wallet',
    'reseller.walletWithdrawals': 'Wallet & Withdrawals',
    'reseller.manageWallet': 'Manage Wallet',
    'reseller.storeSettings': 'Store Settings',
    'reseller.editStoreSettings': 'Edit Store Settings',
    'reseller.accessDenied': 'Access Denied',
    'reseller.accessDeniedDesc': 'You need seller access to view this page',
    
    // Seller Wallet
    'wallet.title': 'Wallet & Withdrawals',
    'wallet.currentBalance': 'Current Balance',
    'wallet.totalEarned': 'Total Earned',
    'wallet.requestWithdrawal': 'Request Withdrawal',
    'wallet.amount': 'Amount (ETB)',
    'wallet.paymentMethod': 'Payment Method',
    'wallet.telebirr': 'Telebirr',
    'wallet.cbe': 'CBE (Commercial Bank of Ethiopia)',
    'wallet.phoneNumber': 'Phone Number',
    'wallet.accountHolderName': 'Account Holder Name',
    'wallet.accountNumber': 'Account Number',
    'wallet.submitRequest': 'Submit Request',
    'wallet.withdrawalHistory': 'Withdrawal History',
    'wallet.noWithdrawals': 'No withdrawal requests yet',
    'wallet.invalidAmount': 'Please enter a valid amount',
    'wallet.insufficientBalance': 'Insufficient balance',
    'wallet.requestSubmitted': 'Withdrawal request submitted',
    
    // Seller Setup
    'setup.title': 'Store Setup',
    'setup.createTitle': 'Create Your Store',
    'setup.editTitle': 'Edit Store Settings',
    'setup.storeName': 'Store Name',
    'setup.storeSlug': 'Store URL Slug',
    'setup.storeUrlPreview': 'Your store will be at:',
    'setup.contactEmail': 'Contact Email',
    'setup.contactPhone': 'Contact Phone',
    'setup.saving': 'Saving...',
    'setup.create': 'Create Store',
    'setup.update': 'Update Store',
    'setup.storeCreated': 'Store created successfully',
    'setup.storeUpdated': 'Store updated successfully',
    
    // Refund categories
    'refund.wrongItem': 'Wrong item received',
    'refund.damaged': 'Item damaged',
    'refund.notAsDescribed': 'Item not as described',
    'refund.noLongerNeed': 'No longer need the item',
    'refund.other': 'Other reason',
    'refund.status.pending': 'Pending',
    'refund.status.approved': 'Approved',
    'refund.status.rejected': 'Rejected',
    'refund.status.processed': 'Processed',
    
    // Apply Seller
    'apply.title': 'Apply to Become a Seller',
    'apply.subtitle': 'Fill in your details to apply as a reseller on our platform',
    'apply.signInRequired': 'Please sign in',
    'apply.signInDesc': 'You need to be signed in to apply as a reseller',
    'apply.personalInfo': 'Personal Information',
    'apply.fullName': 'Full Name',
    'apply.fullNamePlaceholder': 'Enter your full name',
    'apply.email': 'Email Address',
    'apply.emailPlaceholder': 'Enter your email address',
    'apply.uid': 'UID (National ID)',
    'apply.uidPlaceholder': 'Enter your national ID number',
    'apply.age': 'Age',
    'apply.agePlaceholder': 'Enter your age',
    'apply.phone': 'Phone Number',
    'apply.phonePlaceholder': 'Enter your phone number (09XXXXXXXX)',
    'apply.idVerification': 'ID Verification',
    'apply.idFront': 'ID Front Photo',
    'apply.idFrontDesc': 'Take a photo of the front of your ID',
    'apply.idBack': 'ID Back Photo',
    'apply.idBackDesc': 'Take a photo of the back of your ID',
    'apply.faceVerification': 'Face Verification',
    'apply.invalidEmail': 'Invalid Email',
    'apply.invalidEmailDesc': 'Please enter a valid email address',
    'apply.invalidPhone': 'Invalid Phone',
    'apply.invalidPhoneDesc': 'Please enter a valid Ethiopian phone number',
    'apply.invalidAge': 'Invalid Age',
    'apply.invalidAgeDesc': 'You must be at least 18 years old',
    'apply.missingInfo': 'Missing Information',
    'apply.missingInfoDesc': 'Please fill in all fields and upload required photos',
    'apply.duplicateAccount': 'Duplicate Account Detected',
    'apply.duplicateAccountDesc': 'You have already created another reseller account. Only one account per person is allowed.',
    'apply.submitted': 'Application Submitted',
    'apply.submittedDesc': 'Your reseller application has been submitted for review',
    'apply.submitError': 'Failed to submit application',
    'apply.submitting': 'Submitting...',
    'apply.submit': 'Submit Application',
    'apply.yourApplication': 'Your Seller Application',
    'apply.status': 'Status',
    'apply.submittedOn': 'Submitted',
    'apply.adminNotes': 'Admin Notes',
    'apply.setupStore': 'Setup Your Store',
    
    // Face Authentication
    'face.title': 'Face Verification',
    'face.description': 'Complete the following challenges to verify your identity',
    'face.lookCenter': 'Look at the camera',
    'face.turnLeft': 'Turn your head left',
    'face.turnRight': 'Turn your head right',
    'face.blinkEyes': 'Blink your eyes',
    'face.complete': 'Verification complete!',
    'face.hold': 'Hold still...',
    'face.verify': 'Verify',
    'face.required': 'Face Verification Required',
    'face.requiredDesc': 'Please complete face verification to continue',
    'face.successTitle': 'Face Verified',
    'face.successDesc': 'Your face has been verified successfully',
    'face.whyNeeded': 'Why is face verification needed?',
    'face.whyNeededDesc': 'Face verification helps prevent multiple accounts and ensures the security of our platform.',
    'face.verified': 'Face Verified',
    'face.startVerification': 'Start Face Verification',
    
    // Banned User
    'banned.title': 'Account Banned',
    'banned.message': 'Your account has been banned from accessing this platform.',
    'banned.reason': 'Reason:',
    'banned.contactSupport': 'If you believe this is a mistake, please contact our support team.',
    'banned.contactButton': 'Contact Customer Support',
    
    // Notifications
    'notification.resellerApproved': 'Seller Application Approved',
    'notification.resellerApprovedDesc': 'Your reseller application has been approved! You can now set up your store.',
    'notification.resellerRejected': 'Seller Application Rejected',
    'notification.resellerRejectedDesc': 'Your reseller application has been rejected.',
    'notification.newNotification': 'New Notification',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.etb': 'ETB',
  },
  am: {
    // Navbar
    'nav.brand': 'አቤኒ ኤክስፕረስ',
    'nav.browse': 'ምርቶችን ይመልከቱ',
    'nav.request': 'ዕቃ ይጠይቁ',
    'nav.support': 'ድጋፍ',
    'nav.admin': 'አስተዳዳሪ ፓነል',
    'nav.reseller': 'የሻጭ ዳሽቦርድ',
    'nav.signOut': 'ውጣ',
    'nav.signIn': 'ግባ',
    'nav.account': 'መለያ',
    'nav.cart': 'ጋሪ',
    'nav.services': 'አገልግሎቶች',
    'nav.seller': 'የሻጭ ዳሽቦርድ',
    'nav.driver': 'የሾፌር ዳሽቦርድ',
    
    // Language selector
    'lang.select': 'ቋንቋ',
    'lang.en': 'English',
    'lang.am': 'አማርኛ',
    
    // Home page
    'home.hero.title': 'የኢትዮጵያ ራሱን የቻለ ገበያ',
    'home.hero.subtitle': 'ከአካባቢ ሻጮች የተረጋገጡ ምርቶችንና አገልግሎቶችን በኢትዮጵያ ብር ይግዙ — በሾፌሮቻችን አማካኝነት ወደ እርስዎ ይደርሳል።',
    'home.hero.browse': 'ምርቶችን ይመልከቱ',
    'home.hero.request': 'ዕቃ ይጠይቁ',
    'home.features.title': 'ለምን ከኛ ይገዙ?',
    'home.features.delivery': 'ፈጣን ማድረስ',
    'home.features.deliveryDesc': 'በኢትዮጵያ ውስጥ ፈጣን ማድረስ',
    'home.features.payment': 'የአገር ውስጥ ክፍያ',
    'home.features.paymentDesc': 'በCBE ወይም ቴሌብር ይክፈሉ',
    'home.features.support': '24/7 ድጋፍ',
    'home.features.supportDesc': 'በአማርኛ እና በእንግሊዝኛ የደንበኛ ድጋፍ',
    'home.features.secure': 'ደህንነቱ የተጠበቀ ግዢ',
    'home.features.secureDesc': 'ደህንነቱ የተጠበቀ ግብይቶች',
    'home.reseller.title': 'ሻጭ ይሁኑ',
    'home.reseller.subtitle': 'የራስዎን መደብር ይክፈቱ እና ትርፍ ያግኙ',
    'home.reseller.apply': 'ሻጭ ይሁኑ',
    'home.seller.title': 'መድረካችንን ይቀላቀሉ',
    'home.seller.subtitle': 'ሻጭ ወይም ሾፌር ይሁኑ እና ገቢ ማግኘት ይጀምሩ',
    'home.seller.become': 'ሻጭ ይሁኑ',
    'home.seller.apply': 'ሻጭ ይሁኑ',
    'home.driver.become': 'ሾፌር ይሁኑ',
    'home.driver.apply': 'ሾፌር ይሁኑ',
    'home.services.browse': 'አገልግሎቶችን ይመልከቱ',
    
    // Products page
    'products.title': 'ምርቶችን ይመልከቱ',
    'products.subtitle': 'ከአካባቢ ሻጮች የተመረጡ ምርቶች',
    'products.search': 'ምርቶችን ይፈልጉ...',
    'products.showing': 'እያሳየ',
    'products.of': 'ከ',
    'products.products': 'ምርቶች',
    'products.noProducts': 'ገና ምርቶች የሉም። በቅርቡ ይመልከቱ!',
    'products.noMatch': 'ከማጣሪያዎ ጋር የሚዛመድ ምርት አልተገኘም',
    'products.clearFilters': 'ማጣሪያዎችን ያጽዱ',
    'products.freeShipping': 'ነፃ ማጓጓዣ',
    'products.hotDeal': 'ጥሩ ቅናሽ',
    'products.addToCart': 'ወደ ጋሪ ጨምር',
    'products.buyNow': 'አሁን ግዛ',
    'products.cart': 'ጋሪ',
    
    // Filters
    'filters.title': 'ማጣሪያዎች',
    'filters.categories': 'ምድቦች',
    'filters.priceRange': 'የዋጋ ክልል',
    'filters.freeShipping': 'ነፃ ማጓጓዣ ብቻ',
    'filters.reset': 'ማጣሪያዎችን ዳግም አስጀምር',
    'filters.electronics': 'ኤሌክትሮኒክስ',
    'filters.fashion': 'ፋሽን',
    'filters.home': 'ቤት',
    'filters.beauty': 'ውበት',
    'filters.sports': 'ስፖርት',
    'filters.toys': 'መጫወቻዎች',
    'filters.automotive': 'መኪና',
    'filters.other': 'ሌላ',
    
    // Cart page
    'cart.title': 'የግዢ ጋሪ',
    'cart.empty': 'ጋሪዎ ባዶ ነው',
    'cart.browseProducts': 'ምርቶችን ይመልከቱ',
    'cart.items': 'በጋሪ ውስጥ ያሉ ዕቃዎች',
    'cart.checkout': 'ይክፈሉ',
    'cart.shippingAddress': 'የመላኪያ አድራሻ',
    'cart.city': 'ከተማ',
    'cart.phone': 'ስልክ',
    'cart.paymentMethod': 'የክፍያ ዘዴ',
    'cart.selectPayment': 'የክፍያ ዘዴ ይምረጡ',
    'cart.cbe': 'CBE (የኢትዮጵያ ንግድ ባንክ)',
    'cart.telebirr': 'ቴሌብር',
    'cart.paymentInstructions': 'የክፍያ መመሪያ:',
    'cart.transferAmount': 'ጠቅላላ ገንዘቡን ወደዚህ ያስተላልፉ:',
    'cart.paymentProof': 'የክፍያ ማረጋገጫ (አማራጭ)',
    'cart.uploadScreenshot': 'የክፍያ ማረጋገጫ ስክሪንሾት ይስቀሉ',
    'cart.total': 'ጠቅላላ:',
    'cart.placeOrder': 'ትዕዛዝ ያስገቡ',
    'cart.fillShipping': 'እባክዎ ሁሉንም የመላኪያ መረጃ ይሙሉ',
    'cart.selectPaymentMethod': 'እባክዎ የክፍያ ዘዴ ይምረጡ',
    'cart.emptyCart': 'ጋሪዎ ባዶ ነው',
    'cart.orderSuccess': 'ትዕዛዝ በተሳካ ሁኔታ ተልኳል!',
    'cart.orderFailed': 'ትዕዛዝ መላክ አልተሳካም',
    'cart.itemRemoved': 'ዕቃ ከጋሪ ተወግዷል',
    'cart.via': 'በ',
    
    // Store page
    'store.loading': 'መደብር በመጫን ላይ...',
    'store.notFound': 'መደብር አልተገኘም',
    'store.notFoundDesc': 'ይህ መደብር የለም',
    'store.contact': 'አግኙን',
    'store.searchProducts': 'ምርቶችን ይፈልጉ...',
    'store.noProducts': 'ምርቶች የሉም',
    'store.noProductsFound': 'ምርቶች አልተገኙም',
    'store.addedToCart': 'ወደ ጋሪ ተጨምሯል',
    'store.addedToCartDesc': 'ወደ ጋሪ ተጨምሯል',
    'store.report': 'መደብር ሪፖርት አድርግ',
    'store.updateImage': 'ምስል አዘምን',
    'store.uploading': 'በመስቀል ላይ...',
    'store.code': 'ኮድ',
    
    // Auth page
    'auth.welcome': 'እንኳን ደህና መጡ',
    'auth.description': 'ወደ መለያዎ ይግቡ ወይም አዲስ ይፍጠሩ',
    'auth.signIn': 'ግባ',
    'auth.signUp': 'ተመዝገብ',
    'auth.email': 'ኢሜይል',
    'auth.password': 'የይለፍ ቃል',
    'auth.fullName': 'ሙሉ ስም',
    'auth.signingIn': 'በመግባት ላይ...',
    'auth.creatingAccount': 'መለያ በመፍጠር ላይ...',
    'auth.createAccount': 'መለያ ፍጠር',
    'auth.accountCreated': 'መለያ ተፈጠረ! እባክዎ ከመግባትዎ በፊት ኢሜይልዎን ያረጋግጡ።',
    'auth.signedIn': 'በተሳካ ሁኔታ ገብተዋል!',
    'auth.verifyEmail': 'ከመግባትዎ በፊት እባክዎ ኢሜይልዎን ያረጋግጡ።',
    'auth.forgotPassword': 'የይለፍ ቃል ረሱ?',
    'auth.forgotPasswordDesc': 'ኢሜይልዎን ያስገቡ፣ የመቀየሪያ ሊንክ እንልክልዎታለን።',
    'auth.backToLogin': 'ወደ መግቢያ ተመለስ',
    
    // Account page
    'account.title': 'የኔ መለያ',
    'account.yourIds': 'የእርስዎ መታወቂያዎች',
    'account.uid': 'UID',
    'account.id': 'ID',
    'account.copy': 'ቅዳ',
    'account.quoteRequests': 'የዋጋ ጥያቄዎች',
    'account.orders': 'ትዕዛዞች',
    'account.refunds': 'ተመላሾች',
    'account.noQuotes': 'ገና የዋጋ ጥያቄዎች የሉም። ዕቃ ይጠይቁ ለመጀመር!',
    'account.noOrders': 'ገና ትዕዛዞች የሉም። ግዢ ለመጀመር ምርቶችን ይመልከቱ!',
    'account.noRefunds': 'ገና የተመላሽ ጥያቄዎች የሉም።',
    'account.quantity': 'ብዛት',
    'account.requestedOn': 'የተጠየቀበት ቀን',
    'account.items': 'ዕቃዎች',
    'account.total': 'ጠቅላላ',
    'account.shippingDetails': 'የመላኪያ ዝርዝሮች',
    'account.trackingInfo': 'የመከታተያ መረጃ',
    'account.trackPackage': 'ይህንን ቁጥር በመጠቀም ዕቃዎን ይከታተሉ',
    'account.paymentConfirmed': 'ክፍያ ተረጋግጧል',
    'account.orderPreparing': 'ትዕዛዝዎ በመዘጋጀት ላይ ነው። በቅርቡ የመከታተያ ቁጥር ይደርስዎታል!',
    'account.requestRefund': 'ተመላሽ ጠይቅ',
    'account.refundReason': 'የተመላሽ ምክንያት',
    'account.submitRefund': 'የተመላሽ ጥያቄ ላክ',
    'account.placedOn': 'የታዘዘበት ቀን',
    'account.updated': 'የተዘመነ',
    'account.order': 'ትዕዛዝ',
    
    // Support page
    'support.title': 'የደንበኛ ድጋፍ',
    'support.subtitle': 'እርስዎን ለመርዳት እዚህ ነን',
    'support.submitTicket': 'የድጋፍ ቲኬት ላክ',
    'support.yourUserId': 'የእርስዎ ተጠቃሚ መታወቂያ',
    'support.userIdNote': 'ሲገቡ ይህ በራስ ሰር ይሞላል',
    'support.category': 'ምድብ',
    'support.selectCategory': 'ምድብ ይምረጡ',
    'support.subject': 'ርዕሰ ጉዳይ',
    'support.subjectPlaceholder': 'ስለ ችግርዎ አጭር መግለጫ',
    'support.message': 'መልዕክት',
    'support.messagePlaceholder': 'እባክዎ ስለ ችግርዎ ዝርዝሮችን ያቅርቡ...',
    'support.submit': 'ቲኬት ላክ',
    'support.submitting': 'በመላክ ላይ...',
    'support.aiSuggestion': 'በ AI የተጠቆመ መፍትሄ',
    'support.aiNote': 'ይህ አውቶማቲክ ጥቆማ ነው። የድጋፍ ቡድናችን ቲኬትዎን ይገመግማል እና ተጨማሪ እርዳታ ይሰጣል።',
    'support.myTickets': 'የእኔ የድጋፍ ቲኬቶች',
    'support.originalMessage': 'የመጀመሪያ መልዕክት:',
    'support.supportTeam': 'የድጋፍ ቡድን',
    'support.you': 'እርስዎ',
    'support.typeReply': 'ምላሽዎን ይፃፉ...',
    'support.ticketSubmitted': 'ቲኬት ተልኳል',
    'support.ticketSubmittedDesc': 'የድጋፍ ቡድናችን በቅርቡ ምላሽ ይሰጣል',
    'support.replySent': 'ምላሽ ተልኳል',
    'support.replySentDesc': 'መልዕክትዎ ወደ ድጋፍ ተልኳል',
    'support.signInRequired': 'እባክዎ ይግቡ',
    'support.signInRequiredDesc': 'የድጋፍ ቲኬት ለመላክ መግባት አለብዎት',
    'support.missingInfo': 'የጎደለ መረጃ',
    'support.missingInfoDesc': 'እባክዎ ሁሉንም መስኮች ይሙሉ',
    'support.error': 'ስህተት',
    'support.errorDesc': 'ቲኬት መላክ አልተሳካም። እባክዎ እንደገና ይሞክሩ።',
    'support.replyError': 'ምላሽ መላክ አልተሳካም',
    
    // Seller Dashboard
    'reseller.title': 'የሻጭ ዳሽቦርድ',
    'reseller.createStore': 'መደብርዎን ይፍጠሩ',
    'reseller.createStoreDesc': 'መሸጥ ከመጀመርዎ በፊት መደብር መፍጠር አለብዎት።',
    'reseller.createStoreBtn': 'መደብር ፍጠር',
    'reseller.yourIds': 'የእርስዎ መታወቂያዎች',
    'reseller.uid': 'UID',
    'reseller.id': 'ID',
    'reseller.copy': 'ቅዳ',
    'reseller.storeLink': 'የመደብር ሊንክዎ',
    'reseller.open': 'ክፈት',
    'reseller.totalOrders': 'ጠቅላላ ትዕዛዞች',
    'reseller.pendingOrders': 'በመጠባበቅ ላይ ያሉ ትዕዛዞች',
    'reseller.products': 'ምርቶች',
    'reseller.currentBalance': 'የአሁኑ ቀሪ ሂሳብ',
    'reseller.totalEarned': 'ጠቅላላ ገቢ',
    'reseller.manageProducts': 'ምርቶችን አስተዳድር',
    'reseller.orders': 'ትዕዛዞች',
    'reseller.viewOrders': 'ትዕዛዞችን ይመልከቱ',
    'reseller.viewAllOrders': 'ሁሉንም ትዕዛዞች ይመልከቱ',
    'reseller.wallet': 'ኪስ',
    'reseller.walletWithdrawals': 'ኪስ እና ማውጣት',
    'reseller.manageWallet': 'ኪስ አስተዳድር',
    'reseller.storeSettings': 'የመደብር ቅንብሮች',
    'reseller.editStoreSettings': 'የመደብር ቅንብሮችን አርትዕ',
    'reseller.accessDenied': 'መዳረሻ ተከልክሏል',
    'reseller.accessDeniedDesc': 'ይህን ገጽ ለመመልከት የሻጭ መዳረሻ ያስፈልግዎታል',
    
    // Seller Wallet
    'wallet.title': 'ኪስ እና ማውጣት',
    'wallet.currentBalance': 'የአሁኑ ቀሪ ሂሳብ',
    'wallet.totalEarned': 'ጠቅላላ ገቢ',
    'wallet.requestWithdrawal': 'ማውጣት ጠይቅ',
    'wallet.amount': 'መጠን (ETB)',
    'wallet.paymentMethod': 'የክፍያ ዘዴ',
    'wallet.telebirr': 'ቴሌብር',
    'wallet.cbe': 'CBE (የኢትዮጵያ ንግድ ባንክ)',
    'wallet.phoneNumber': 'ስልክ ቁጥር',
    'wallet.accountHolderName': 'የመለያ ባለቤት ስም',
    'wallet.accountNumber': 'የመለያ ቁጥር',
    'wallet.submitRequest': 'ጥያቄ ላክ',
    'wallet.withdrawalHistory': 'የማውጣት ታሪክ',
    'wallet.noWithdrawals': 'ገና የማውጣት ጥያቄዎች የሉም',
    'wallet.invalidAmount': 'እባክዎ ትክክለኛ መጠን ያስገቡ',
    'wallet.insufficientBalance': 'በቂ ቀሪ ሂሳብ የለም',
    'wallet.requestSubmitted': 'የማውጣት ጥያቄ ተልኳል',
    
    // Seller Setup
    'setup.title': 'የመደብር ማዋቀር',
    'setup.createTitle': 'መደብርዎን ይፍጠሩ',
    'setup.editTitle': 'የመደብር ቅንብሮችን አርትዕ',
    'setup.storeName': 'የመደብር ስም',
    'setup.storeSlug': 'የመደብር URL Slug',
    'setup.storeUrlPreview': 'መደብርዎ የሚገኝበት:',
    'setup.contactEmail': 'የመገኛ ኢሜይል',
    'setup.contactPhone': 'የመገኛ ስልክ',
    'setup.saving': 'በማስቀመጥ ላይ...',
    'setup.create': 'መደብር ፍጠር',
    'setup.update': 'መደብር አዘምን',
    'setup.storeCreated': 'መደብር በተሳካ ሁኔታ ተፈጠረ',
    'setup.storeUpdated': 'መደብር በተሳካ ሁኔታ ተዘመነ',
    
    // Refund categories
    'refund.wrongItem': 'የተሳሳተ ዕቃ ደረሰ',
    'refund.damaged': 'ዕቃ ተበላሽቷል',
    'refund.notAsDescribed': 'ዕቃ እንደተገለጸው አይደለም',
    'refund.noLongerNeed': 'ዕቃ ከአሁን በኋላ አያስፈልገኝም',
    'refund.other': 'ሌላ ምክንያት',
    'refund.status.pending': 'በመጠባበቅ ላይ',
    'refund.status.approved': 'ተቀባይነት አግኝቷል',
    'refund.status.rejected': 'ተቀባይነት አላገኘም',
    'refund.status.processed': 'ተሠርቷል',
    
    // Apply Seller
    'apply.title': 'ሻጭ ለመሆን ያመልክቱ',
    'apply.subtitle': 'በእኛ መድረክ ላይ ሻጭ ለመሆን ዝርዝሮችዎን ይሙሉ',
    'apply.signInRequired': 'እባክዎ ይግቡ',
    'apply.signInDesc': 'ሻጭ ለመሆን ማመልከት መግባት አለብዎት',
    'apply.personalInfo': 'የግል መረጃ',
    'apply.fullName': 'ሙሉ ስም',
    'apply.fullNamePlaceholder': 'ሙሉ ስምዎን ያስገቡ',
    'apply.email': 'ኢሜይል አድራሻ',
    'apply.emailPlaceholder': 'ኢሜይል አድራሻዎን ያስገቡ',
    'apply.uid': 'UID (ብሔራዊ መታወቂያ)',
    'apply.uidPlaceholder': 'ብሔራዊ መታወቂያ ቁጥርዎን ያስገቡ',
    'apply.age': 'ዕድሜ',
    'apply.agePlaceholder': 'ዕድሜዎን ያስገቡ',
    'apply.phone': 'ስልክ ቁጥር',
    'apply.phonePlaceholder': 'ስልክ ቁጥርዎን ያስገቡ (09XXXXXXXX)',
    'apply.idVerification': 'የመታወቂያ ማረጋገጫ',
    'apply.idFront': 'የመታወቂያ ፊት ፎቶ',
    'apply.idFrontDesc': 'የመታወቂያዎን ፊት ለፊት ፎቶ ያንሱ',
    'apply.idBack': 'የመታወቂያ ጀርባ ፎቶ',
    'apply.idBackDesc': 'የመታወቂያዎን ጀርባ ፎቶ ያንሱ',
    'apply.faceVerification': 'የፊት ማረጋገጫ',
    'apply.invalidEmail': 'ልክ ያልሆነ ኢሜይል',
    'apply.invalidEmailDesc': 'እባክዎ ትክክለኛ ኢሜይል አድራሻ ያስገቡ',
    'apply.invalidPhone': 'ልክ ያልሆነ ስልክ',
    'apply.invalidPhoneDesc': 'እባክዎ ትክክለኛ የኢትዮጵያ ስልክ ቁጥር ያስገቡ',
    'apply.invalidAge': 'ልክ ያልሆነ ዕድሜ',
    'apply.invalidAgeDesc': 'ቢያንስ 18 ዓመት መሆን አለብዎት',
    'apply.missingInfo': 'የጎደለ መረጃ',
    'apply.missingInfoDesc': 'እባክዎ ሁሉንም መስኮች ይሙሉ እና አስፈላጊ ፎቶዎችን ይስቀሉ',
    'apply.duplicateAccount': 'ድግግሞሽ መለያ ተገኝቷል',
    'apply.duplicateAccountDesc': 'ቀደም ሲል ሌላ የሻጭ መለያ ፈጥረዋል። በአንድ ሰው አንድ መለያ ብቻ ይፈቀዳል።',
    'apply.submitted': 'ማመልከቻ ተልኳል',
    'apply.submittedDesc': 'የሻጭ ማመልከቻዎ ለግምገማ ተልኳል',
    'apply.submitError': 'ማመልከቻ መላክ አልተሳካም',
    'apply.submitting': 'በመላክ ላይ...',
    'apply.submit': 'ማመልከቻ ላክ',
    'apply.yourApplication': 'የሻጭ ማመልከቻዎ',
    'apply.status': 'ሁኔታ',
    'apply.submittedOn': 'የተላከበት',
    'apply.adminNotes': 'የአስተዳዳሪ ማስታወሻዎች',
    'apply.setupStore': 'መደብርዎን ያዋቅሩ',
    
    // Face Authentication
    'face.title': 'የፊት ማረጋገጫ',
    'face.description': 'ማንነትዎን ለማረጋገጥ የሚከተሉትን ተግዳሮቶች ያጠናቅቁ',
    'face.lookCenter': 'ወደ ካሜራው ይመልከቱ',
    'face.turnLeft': 'ራስዎን ወደ ግራ ያዙሩ',
    'face.turnRight': 'ራስዎን ወደ ቀኝ ያዙሩ',
    'face.blinkEyes': 'ዓይንዎን ያብጩ',
    'face.complete': 'ማረጋገጫ ተጠናቋል!',
    'face.hold': 'ይጠብቁ...',
    'face.verify': 'አረጋግጥ',
    'face.required': 'የፊት ማረጋገጫ ያስፈልጋል',
    'face.requiredDesc': 'እባክዎ ለመቀጠል የፊት ማረጋገጫ ያጠናቅቁ',
    'face.successTitle': 'ፊት ተረጋግጧል',
    'face.successDesc': 'ፊትዎ በተሳካ ሁኔታ ተረጋግጧል',
    'face.whyNeeded': 'የፊት ማረጋገጫ ለምን ያስፈልጋል?',
    'face.whyNeededDesc': 'የፊት ማረጋገጫ ብዙ መለያዎችን ለመከላከል እና የመድረካችንን ደህንነት ለማረጋገጥ ይረዳል።',
    'face.verified': 'ፊት ተረጋግጧል',
    'face.startVerification': 'የፊት ማረጋገጫ ጀምር',
    
    // Banned User
    'banned.title': 'መለያ ታግዷል',
    'banned.message': 'መለያዎ ይህን መድረክ ከመጠቀም ታግዷል።',
    'banned.reason': 'ምክንያት:',
    'banned.contactSupport': 'ይህ ስህተት ነው ብለው ካሰቡ፣ እባክዎ የድጋፍ ቡድናችንን ያነጋግሩ።',
    'banned.contactButton': 'የደንበኛ ድጋፍ ያግኙ',
    
    // Notifications
    'notification.resellerApproved': 'የሻጭ ማመልከቻ ተቀባይነት አግኝቷል',
    'notification.resellerApprovedDesc': 'የሻጭ ማመልከቻዎ ተቀባይነት አግኝቷል! አሁን መደብርዎን ማዋቀር ይችላሉ።',
    'notification.resellerRejected': 'የሻጭ ማመልከቻ ተቀባይነት አላገኘም',
    'notification.resellerRejectedDesc': 'የሻጭ ማመልከቻዎ ተቀባይነት አላገኘም።',
    'notification.newNotification': 'አዲስ ማሳወቂያ',
    
    // Common
    'common.loading': 'በመጫን ላይ...',
    'common.error': 'ስህተት',
    'common.success': 'ተሳክቷል',
    'common.cancel': 'ሰርዝ',
    'common.confirm': 'አረጋግጥ',
    'common.save': 'አስቀምጥ',
    'common.delete': 'ሰርዝ',
    'common.edit': 'አርትዕ',
    'common.view': 'ይመልከቱ',
    'common.back': 'ተመለስ',
    'common.next': 'ቀጣይ',
    'common.previous': 'ቀዳሚ',
    'common.etb': 'ብር',
  },
  // Afaan Oromo
  om: {
    'nav.brand': 'Abeni Express',
    'nav.browse': 'Oomishaalee Ilaali',
    'nav.request': 'Meeshaa Gaafadhu',
    'nav.support': 'Deeggarsa',
    'nav.admin': 'Paanaalii Bulchaa',
    'nav.reseller': 'Daashboordii Gurguraa',
    'nav.signOut': 'Bahi',
    'nav.signIn': 'Seeni',
    'nav.account': 'Akkaawuntii',
    'nav.cart': 'Galmee',
    'nav.services': 'Tajaajila',
    'nav.seller': 'Daashboordii Gurguraa',
    'nav.driver': 'Daashboordii Konkolaachisaa',
    'lang.select': 'Afaan',
    'lang.en': 'English',
    'lang.am': 'አማርኛ',
    'lang.om': 'Afaan Oromoo',
    'lang.ti': 'ትግርኛ',
    'home.hero.title': 'Gabaa Walaba Itoophiyaa',
    'home.hero.subtitle': 'Oomishaalee fi tajaajila mirkaneeffaman gurgurtoota naannoo irraa Birrii Itoophiyaatiin bitadhu — geejjibsiistota keenyaan ni dhihaata.',
    'home.hero.browse': 'Oomishaalee Ilaali',
    'home.hero.request': 'Meeshaa Gaafadhu',
    'home.features.title': 'Maaliif Nu bira Bitattu?',
    'home.features.delivery': 'Geejjiba Saffisaa',
    'home.features.deliveryDesc': 'Itoophiyaa keessatti geejjiba saffisaa',
    'home.features.payment': 'Kaffaltii Naannoo',
    'home.features.paymentDesc': 'CBE ykn Telebirr fayyadamiitii kaffali',
    'home.features.support': 'Deeggarsa 24/7',
    'home.features.supportDesc': 'Afaan Oromoo, Amaariffaa fi Ingiliffaa',
    'home.features.secure': 'Bittaa Nagayaa',
    'home.features.secureDesc': 'Daldala nagaa qabu',
    'home.reseller.title': 'Gurguraa Ta’i',
    'home.reseller.subtitle': 'Suuqii kee banadhuu buʼaa argadhu',
    'home.reseller.apply': 'Gurguraa Ta’i',
    'home.seller.title': 'Pilaatformii Keenyatti Makami',
    'home.seller.subtitle': 'Gurguraa ykn konkolaachisaa taʼiitii galii argadhu',
    'home.seller.become': 'Gurguraa Ta’i',
    'home.seller.apply': 'Gurguraa Ta’i',
    'home.driver.become': 'Konkolaachisaa Ta’i',
    'home.driver.apply': 'Konkolaachisaa Ta’i',
    'home.services.browse': 'Tajaajila Ilaali',
    'products.title': 'Oomishaalee Ilaali',
    'products.subtitle': 'Oomishaalee filatamoo gurgurtoota naannoo irraa',
    'products.search': 'Oomishaalee barbaadi...',
    'products.showing': 'Argisiisa',
    'products.of': 'irraa',
    'products.products': 'oomishaalee',
    'products.noProducts': 'Oomishaan hin jiru. Booda deebi’ii ilaali!',
    'products.noMatch': 'Filannoo keetiin oomishaan hin argamne',
    'products.clearFilters': 'Filannoo Balleessi',
    'products.freeShipping': 'Geejjiba Bilisaa',
    'products.hotDeal': 'Gatii Salphaa',
    'products.addToCart': 'Galmeetti Dabali',
    'products.buyNow': 'Amma Bitadhu',
    'products.cart': 'Galmee',
    'filters.title': 'Filannoo',
    'filters.categories': 'Gosoota',
    'filters.priceRange': 'Sadarkaa Gatii',
    'filters.freeShipping': 'Geejjiba Bilisaa Qofa',
    'filters.reset': 'Filannoo Haaromsi',
    'filters.electronics': 'Elektirooniksii',
    'filters.fashion': 'Faashinii',
    'filters.home': 'Mana',
    'filters.beauty': 'Miidhagina',
    'filters.sports': 'Ispoortii',
    'filters.toys': 'Meeshaa Taphaa',
    'filters.automotive': 'Konkolaataa',
    'filters.other': 'Kan biraa',
    'cart.title': 'Galmee Bittaa',
    'cart.empty': 'Galmeen kee duwwaa dha',
    'cart.browseProducts': 'Oomishaalee Ilaali',
    'cart.items': 'Meeshaalee Galmee',
    'cart.checkout': 'Kaffali',
    'cart.shippingAddress': 'Teessoo Geejjibaa',
    'cart.city': 'Magaalaa',
    'cart.phone': 'Bilbila',
    'cart.paymentMethod': 'Mala Kaffaltii',
    'cart.selectPayment': 'Mala kaffaltii filadhu',
    'cart.cbe': 'CBE (Baankii Daldalaa Itoophiyaa)',
    'cart.telebirr': 'Telebirr',
    'cart.paymentInstructions': 'Qajeelfama Kaffaltii:',
    'cart.transferAmount': 'Waliigalaa gara kanaa dabarsi:',
    'cart.paymentProof': 'Ragaa Kaffaltii (Filannoo)',
    'cart.uploadScreenshot': 'Suuraa mirkaneessa kaffaltii ol-fe’i',
    'cart.total': 'Waliigala:',
    'cart.placeOrder': 'Ajaja Galchi',
    'cart.fillShipping': 'Odeeffannoo geejjibaa hunda guuti',
    'cart.selectPaymentMethod': 'Mala kaffaltii filadhu',
    'cart.emptyCart': 'Galmeen kee duwwaa dha',
    'cart.orderSuccess': 'Ajajni milkaaʼinaan galee!',
    'cart.orderFailed': 'Ajajni hin milkoofne',
    'cart.itemRemoved': 'Meeshaan galmee irraa haqame',
    'cart.via': 'karaa',
    'store.loading': 'Suuqiin fe’amaa jira...',
    'store.notFound': 'Suuqiin Hin Argamne',
    'store.notFoundDesc': 'Suuqiin kun hin jiru',
    'store.contact': 'Nu Qunnami',
    'store.searchProducts': 'Oomishaalee barbaadi...',
    'store.noProducts': 'Oomishaan hin jiru',
    'store.noProductsFound': 'Oomishaan hin argamne',
    'store.addedToCart': 'Galmeetti Dabalame',
    'store.addedToCartDesc': 'galmeetti dabalame',
    'store.report': 'Suuqii Gabaasi',
    'store.updateImage': 'Suuraa Haaromsi',
    'store.uploading': 'Ol-fe’aa jira...',
    'store.code': 'Koodii',
    'auth.welcome': 'Baga Nagaan Dhufte',
    'auth.description': 'Akkaawuntii keetitti seeni ykn haaraa uumi',
    'auth.signIn': 'Seeni',
    'auth.signUp': 'Galmaa’i',
    'auth.email': 'Imeelii',
    'auth.password': 'Jecha Iccitii',
    'auth.fullName': 'Maqaa Guutuu',
    'auth.signingIn': 'Seenaa jira...',
    'auth.creatingAccount': 'Akkaawuntii uumaa jira...',
    'auth.createAccount': 'Akkaawuntii Uumi',
    'auth.accountCreated': 'Akkaawuntiin uumameera! Imeelii kee ilaali.',
    'auth.signedIn': 'Milkaa’inaan seentee jirta!',
    'auth.verifyEmail': 'Osoo hin seeniin imeelii kee mirkaneessi.',
    'auth.forgotPassword': 'Jecha iccitii dagatte?',
    'auth.forgotPasswordDesc': 'Imeelii kee galchi geessuu haaromsuutiin ni ergama.',
    'auth.backToLogin': 'Gara Seenuu Deebi’i',
    'account.title': 'Akkaawuntii Koo',
    'account.yourIds': 'IDs Kee',
    'account.uid': 'UID',
    'account.id': 'ID',
    'account.copy': 'Garagalchi',
    'account.quoteRequests': 'Gaaffilee Gatii',
    'account.orders': 'Ajajoota',
    'account.refunds': 'Deebisuu',
    'account.noQuotes': 'Gaaffiin gatii hin jiru.',
    'account.noOrders': 'Ajajni hin jiru. Bittaa jalqabi!',
    'account.noRefunds': 'Deebisuun hin jiru.',
    'account.quantity': 'Baayina',
    'account.requestedOn': 'Gaafataman',
    'account.items': 'Meeshaalee',
    'account.total': 'Waliigala',
    'account.shippingDetails': 'Ibsa Geejjibaa',
    'account.trackingInfo': 'Odeeffannoo Hordoffii',
    'account.trackPackage': 'Lakkoofsa kanaan meeshaa kee hordofi',
    'account.paymentConfirmed': 'Kaffaltiin Mirkanaa’e',
    'account.orderPreparing': 'Ajajni kee qophaa’aa jira.',
    'account.requestRefund': 'Deebisuu Gaafadhu',
    'account.refundReason': 'Sababa Deebisuu',
    'account.submitRefund': 'Gaaffii Deebisuu Ergi',
    'account.placedOn': 'Ajaja galee',
    'account.updated': 'Haaromfame',
    'account.order': 'Ajaja',
    'support.title': 'Deeggarsa Maamilaa',
    'support.subtitle': 'Si gargaaruuf as jirra',
    'support.submitTicket': 'Tikkeetii Deeggarsaa Ergi',
    'support.yourUserId': 'ID Fayyadamaa Kee',
    'support.userIdNote': 'Yeroo seentu ofumaan guutama',
    'support.category': 'Gosa',
    'support.selectCategory': 'Gosa filadhu',
    'support.subject': 'Mata Duree',
    'support.subjectPlaceholder': 'Ibsa gabaabaa rakkoo kee',
    'support.message': 'Ergaa',
    'support.messagePlaceholder': 'Ibsa bal’aa kenni...',
    'support.submit': 'Tikkeetii Ergi',
    'support.submitting': 'Ergaa jira...',
    'support.myTickets': 'Tikkeetii Koo',
    'support.you': 'Ati',
    'support.supportTeam': 'Garee Deeggarsaa',
    'support.typeReply': 'Deebii kee barreessi...',
    'reseller.title': 'Daashboordii Gurguraa',
    'reseller.createStore': 'Suuqii Kee Uumi',
    'reseller.createStoreBtn': 'Suuqii Uumi',
    'reseller.storeLink': 'Liinkii Suuqii Keetii',
    'reseller.open': 'Bani',
    'reseller.totalOrders': 'Waliigala Ajaja',
    'reseller.pendingOrders': 'Ajaja Eegaa jiru',
    'reseller.products': 'Oomishaalee',
    'reseller.currentBalance': 'Baalansii Ammaa',
    'reseller.totalEarned': 'Waliigala Argame',
    'reseller.manageProducts': 'Oomisha Bulchi',
    'reseller.orders': 'Ajajoota',
    'reseller.viewOrders': 'Ajajoota Ilaali',
    'reseller.wallet': 'Borsaa',
    'reseller.walletWithdrawals': 'Borsaa fi Baasuu',
    'wallet.title': 'Borsaa fi Baasuu',
    'wallet.currentBalance': 'Baalansii Ammaa',
    'wallet.totalEarned': 'Waliigala Argame',
    'wallet.requestWithdrawal': 'Baasuu Gaafadhu',
    'wallet.amount': 'Hamma (ETB)',
    'wallet.paymentMethod': 'Mala Kaffaltii',
    'wallet.telebirr': 'Telebirr',
    'wallet.cbe': 'CBE',
    'wallet.phoneNumber': 'Lakkoofsa Bilbilaa',
    'wallet.accountHolderName': 'Maqaa Abbaa Akkaawuntii',
    'wallet.accountNumber': 'Lakkoofsa Akkaawuntii',
    'wallet.submitRequest': 'Gaaffii Ergi',
    'wallet.withdrawalHistory': 'Seenaa Baasuu',
    'wallet.noWithdrawals': 'Baasuun hin jiru',
    'setup.storeName': 'Maqaa Suuqii',
    'setup.contactEmail': 'Imeelii Qunnamtii',
    'setup.contactPhone': 'Bilbila Qunnamtii',
    'setup.saving': 'Olkaa’aa jira...',
    'setup.create': 'Suuqii Uumi',
    'setup.update': 'Suuqii Haaromsi',
    'apply.title': 'Gurguraa Ta’uuf Iyyachuu',
    'apply.fullName': 'Maqaa Guutuu',
    'apply.email': 'Imeelii',
    'apply.phone': 'Bilbila',
    'apply.age': 'Umurii',
    'apply.submit': 'Iyyata Ergi',
    'apply.submitting': 'Ergaa jira...',
    'apply.status': 'Haala',
    'banned.title': 'Akkaawuntiin Dhorkameera',
    'banned.message': 'Akkaawuntiin kee pilaatformii kana fayyadamuu dhorkameera.',
    'banned.reason': 'Sababa:',
    'banned.contactSupport': 'Dogongora yoo ta’e, deeggarsa nu qunnami.',
    'banned.contactButton': 'Deeggarsa Qunnami',
    'notification.newNotification': 'Beeksisa Haaraa',
    'common.loading': 'Fe’amaa jira...',
    'common.error': 'Dogoggora',
    'common.success': 'Milkaa’ina',
    'common.cancel': 'Haqi',
    'common.confirm': 'Mirkaneessi',
    'common.save': 'Olkaa’i',
    'common.delete': 'Balleessi',
    'common.edit': 'Gulaali',
    'common.view': 'Ilaali',
    'common.back': 'Duubatti',
    'common.next': 'Itti aanu',
    'common.previous': 'Kan duraa',
    'common.etb': 'ETB',
  },
  // Tigrinya
  ti: {
    'nav.brand': 'ኣቤኒ ኤክስፕረስ',
    'nav.browse': 'ምህርቲ ርአ',
    'nav.request': 'ኣቕሓ ሓትት',
    'nav.support': 'ደገፍ',
    'nav.admin': 'ናይ ኣመሓዳሪ ፓነል',
    'nav.reseller': 'ናይ ሸያጢ ዳሽቦርድ',
    'nav.signOut': 'ውጻእ',
    'nav.signIn': 'እቶ',
    'nav.account': 'ሕሳብ',
    'nav.cart': 'ዓረብያ',
    'nav.services': 'ኣገልግሎታት',
    'nav.seller': 'ናይ ሸያጢ ዳሽቦርድ',
    'nav.driver': 'ናይ ዘዋሪ ዳሽቦርድ',
    'lang.select': 'ቋንቋ',
    'lang.en': 'English',
    'lang.am': 'አማርኛ',
    'lang.om': 'Afaan Oromoo',
    'lang.ti': 'ትግርኛ',
    'home.hero.title': 'ናጻ ዕዳጋ ኢትዮጵያ',
    'home.hero.subtitle': 'ካብ ናይ ከባቢ ሸየጥቲ ዝተረጋገጹ ምህርትን ኣገልግሎትን ብኢትዮጵያ ብር ግዙ — ብዘወርቲ ናባኹም ይመጽእ።',
    'home.hero.browse': 'ምህርቲ ርአ',
    'home.hero.request': 'ኣቕሓ ሓትት',
    'home.features.title': 'ስለምንታይ ካባና ትገዝኡ?',
    'home.features.delivery': 'ቅልጡፍ ምብጻሕ',
    'home.features.deliveryDesc': 'ኣብ ኢትዮጵያ ቅልጡፍ ምብጻሕ',
    'home.features.payment': 'ናይ ውሽጢ ዓዲ ክፍሊት',
    'home.features.paymentDesc': 'ብCBE ወይ ቴሌብር ክፈሉ',
    'home.features.support': 'ደገፍ 24/7',
    'home.features.supportDesc': 'ብትግርኛ፣ ኣምሓርኛ፣ እንግሊዝኛ',
    'home.features.secure': 'ውሑስ ግዥ',
    'home.features.secureDesc': 'ውሑስ ንግዲ',
    'home.reseller.title': 'ሸያጢ ኹን',
    'home.reseller.subtitle': 'ናይ ገዛእ ርእስኻ ዱካን ኸፍት ትርፊ ኣተኣኻኸብ',
    'home.reseller.apply': 'ሸያጢ ኹን',
    'home.seller.title': 'ናብ መድረኽና ተጸምበር',
    'home.seller.subtitle': 'ሸያጢ ወይ ዘዋሪ ኹን እቶት ኣተኣኻኸብ',
    'home.seller.become': 'ሸያጢ ኹን',
    'home.seller.apply': 'ሸያጢ ኹን',
    'home.driver.become': 'ዘዋሪ ኹን',
    'home.driver.apply': 'ዘዋሪ ኹን',
    'home.services.browse': 'ኣገልግሎታት ርአ',
    'products.title': 'ምህርቲ ርአ',
    'products.subtitle': 'ካብ ናይ ከባቢ ሸየጥቲ ዝተመርጹ ምህርቲ',
    'products.search': 'ምህርቲ ድለ...',
    'products.showing': 'ይርአ',
    'products.of': 'ካብ',
    'products.products': 'ምህርቲ',
    'products.noProducts': 'ገና ምህርቲ የለን።',
    'products.noMatch': 'ምስ ማጻረይ ዝሰማማዕ ኣይተረኽበን',
    'products.clearFilters': 'ማጻረይ ኣጽርዩ',
    'products.freeShipping': 'ናጻ ምጉዕዓዝ',
    'products.hotDeal': 'ጽቡቕ ዋጋ',
    'products.addToCart': 'ናብ ዓረብያ ወስኽ',
    'products.buyNow': 'ሕጂ ግዛእ',
    'products.cart': 'ዓረብያ',
    'filters.title': 'ማጻረይ',
    'filters.categories': 'ምድብ',
    'filters.priceRange': 'ደረጃ ዋጋ',
    'filters.freeShipping': 'ናጻ ምጉዕዓዝ ጥራይ',
    'filters.reset': 'ማጻረይ ደገም',
    'filters.electronics': 'ኤለክትሮኒክስ',
    'filters.fashion': 'ፋሽን',
    'filters.home': 'ገዛ',
    'filters.beauty': 'ጽባቐ',
    'filters.sports': 'ስፖርት',
    'filters.toys': 'መጻወቲ',
    'filters.automotive': 'መኪና',
    'filters.other': 'ካልእ',
    'cart.title': 'ናይ ግዥ ዓረብያ',
    'cart.empty': 'ዓረብያኻ ባዶ እያ',
    'cart.browseProducts': 'ምህርቲ ርአ',
    'cart.items': 'ኣብ ዓረብያ ዘለዉ',
    'cart.checkout': 'ክፈል',
    'cart.shippingAddress': 'ኣድራሻ ምብጻሕ',
    'cart.city': 'ከተማ',
    'cart.phone': 'ስልኪ',
    'cart.paymentMethod': 'ኣገባብ ክፍሊት',
    'cart.selectPayment': 'ኣገባብ ክፍሊት ምረጽ',
    'cart.cbe': 'CBE',
    'cart.telebirr': 'ቴሌብር',
    'cart.paymentInstructions': 'መምርሒ ክፍሊት:',
    'cart.transferAmount': 'ጠቕላላ ገንዘብ ናብዚ ኣመሓላልፍ:',
    'cart.paymentProof': 'መረጋገጺ ክፍሊት (ኣማራጺ)',
    'cart.uploadScreenshot': 'ስክሪንሾት ክፍሊት ኣቐምጥ',
    'cart.total': 'ጠቕላላ:',
    'cart.placeOrder': 'ትእዛዝ ኣቐምጥ',
    'cart.fillShipping': 'ኩሉ ሓበሬታ ምጉዕዓዝ ምላእ',
    'cart.selectPaymentMethod': 'ኣገባብ ክፍሊት ምረጽ',
    'cart.emptyCart': 'ዓረብያኻ ባዶ እያ',
    'cart.orderSuccess': 'ትእዛዝ ብዓወት ተላኢኹ!',
    'cart.orderFailed': 'ትእዛዝ ኣይተላኣኸን',
    'cart.itemRemoved': 'ኣቕሓ ካብ ዓረብያ ተኣልዩ',
    'cart.via': 'ብ',
    'store.loading': 'ዱካን ይጽዓን ኣሎ...',
    'store.notFound': 'ዱካን ኣይተረኽበን',
    'store.notFoundDesc': 'እዚ ዱካን የልቦን',
    'store.contact': 'ርኸቡና',
    'store.searchProducts': 'ምህርቲ ድለ...',
    'store.noProducts': 'ምህርቲ የለን',
    'store.noProductsFound': 'ምህርቲ ኣይተረኽበን',
    'store.addedToCart': 'ናብ ዓረብያ ተወሲኹ',
    'store.addedToCartDesc': 'ናብ ዓረብያ ተወሲኹ',
    'store.report': 'ዱካን ሪፖርት ግበር',
    'store.updateImage': 'ስእሊ ኣሐድስ',
    'store.uploading': 'ይጽዓን ኣሎ...',
    'store.code': 'ኮድ',
    'auth.welcome': 'እንኳዕ ብድሓን መጻእካ',
    'auth.description': 'ናብ ሕሳብካ እቶ ወይ ሓድሽ ፍጠር',
    'auth.signIn': 'እቶ',
    'auth.signUp': 'ተመዝገብ',
    'auth.email': 'ኢሜይል',
    'auth.password': 'መሕለፊ ቃል',
    'auth.fullName': 'ምሉእ ስም',
    'auth.signingIn': 'ይኣቱ ኣሎ...',
    'auth.creatingAccount': 'ሕሳብ ይፍጠር ኣሎ...',
    'auth.createAccount': 'ሕሳብ ፍጠር',
    'auth.accountCreated': 'ሕሳብ ተፈጢሩ! ኢሜይልካ ኣረጋግጽ።',
    'auth.signedIn': 'ብዓወት ኣቲኻ!',
    'auth.verifyEmail': 'ቅድሚ ምእታው ኢሜይልካ ኣረጋግጽ።',
    'auth.forgotPassword': 'መሕለፊ ቃል ረሲዕካ?',
    'auth.forgotPasswordDesc': 'ኢሜይልካ ኣቕርብ፣ ናይ ምሕዳስ መላግቦ ክንልእኸልካ ኢና።',
    'auth.backToLogin': 'ናብ ምእታው ተመለስ',
    'account.title': 'ናተይ ሕሳብ',
    'account.yourIds': 'መንነትካ',
    'account.uid': 'UID',
    'account.id': 'ID',
    'account.copy': 'ቅዳሕ',
    'account.orders': 'ትእዛዛት',
    'account.refunds': 'ናይ ገንዘብ ምምላስ',
    'account.noOrders': 'ገና ትእዛዝ የለን።',
    'account.noRefunds': 'ገና ናይ ገንዘብ ምምላስ የለን።',
    'account.quantity': 'ብዝሒ',
    'account.total': 'ጠቕላላ',
    'account.order': 'ትእዛዝ',
    'support.title': 'ናይ ዓሚል ደገፍ',
    'support.subtitle': 'ንኽንሕግዘኩም ኣብዚ ኢና',
    'support.submitTicket': 'ናይ ደገፍ ቲኬት ልኣኽ',
    'support.category': 'ምድብ',
    'support.subject': 'ኣርእስቲ',
    'support.message': 'መልእኽቲ',
    'support.submit': 'ልኣኽ',
    'support.submitting': 'ይልኣኽ ኣሎ...',
    'support.myTickets': 'ናተይ ቲኬታት',
    'support.you': 'ንስኻ',
    'support.supportTeam': 'ጉጅለ ደገፍ',
    'support.typeReply': 'መልስኻ ጽሓፍ...',
    'reseller.title': 'ናይ ሸያጢ ዳሽቦርድ',
    'reseller.createStore': 'ዱካንካ ፍጠር',
    'reseller.createStoreBtn': 'ዱካን ፍጠር',
    'reseller.totalOrders': 'ጠቕላላ ትእዛዛት',
    'reseller.pendingOrders': 'ተጸበይቲ ትእዛዛት',
    'reseller.products': 'ምህርቲ',
    'reseller.currentBalance': 'ህሉው ሚዛን',
    'reseller.totalEarned': 'ጠቕላላ እቶት',
    'reseller.manageProducts': 'ምህርቲ ኣመሓድር',
    'reseller.orders': 'ትእዛዛት',
    'reseller.wallet': 'ቦርሳ',
    'wallet.title': 'ቦርሳን ምውጻእን',
    'wallet.currentBalance': 'ህሉው ሚዛን',
    'wallet.totalEarned': 'ጠቕላላ እቶት',
    'wallet.requestWithdrawal': 'ምውጻእ ሕተት',
    'wallet.amount': 'መጠን (ETB)',
    'wallet.paymentMethod': 'ኣገባብ ክፍሊት',
    'wallet.telebirr': 'ቴሌብር',
    'wallet.cbe': 'CBE',
    'wallet.phoneNumber': 'ቁጽሪ ስልኪ',
    'wallet.accountHolderName': 'ስም ወናኒ ሕሳብ',
    'wallet.accountNumber': 'ቁጽሪ ሕሳብ',
    'wallet.submitRequest': 'ሕቶ ልኣኽ',
    'wallet.withdrawalHistory': 'ታሪኽ ምውጻእ',
    'wallet.noWithdrawals': 'ገና ናይ ምውጻእ ሕቶ የለን',
    'setup.storeName': 'ስም ዱካን',
    'setup.contactEmail': 'ኢሜይል ርክብ',
    'setup.contactPhone': 'ቁጽሪ ስልኪ',
    'setup.saving': 'ይቕመጥ ኣሎ...',
    'setup.create': 'ዱካን ፍጠር',
    'setup.update': 'ኣሐድስ',
    'apply.title': 'ሸያጢ ንምዃን ኣመልክት',
    'apply.fullName': 'ምሉእ ስም',
    'apply.email': 'ኢሜይል',
    'apply.phone': 'ስልኪ',
    'apply.age': 'ዕድመ',
    'apply.submit': 'ኣመልክት',
    'apply.submitting': 'ይልኣኽ ኣሎ...',
    'apply.status': 'ኩነታት',
    'banned.title': 'ሕሳብ ተኣጊዱ',
    'banned.message': 'ሕሳብካ ካብዚ መድረኽ ተኣጊዱ።',
    'banned.reason': 'ምኽንያት:',
    'banned.contactSupport': 'ጌጋ እዩ ኢልካ እንተሓሲብካ፣ ደገፍ ርኸብ።',
    'banned.contactButton': 'ደገፍ ርኸብ',
    'notification.newNotification': 'ሓድሽ ምልክታ',
    'common.loading': 'ይጽዓን ኣሎ...',
    'common.error': 'ጌጋ',
    'common.success': 'ዕዉት',
    'common.cancel': 'ሰርዝ',
    'common.confirm': 'ኣረጋግጽ',
    'common.save': 'ኣቐምጥ',
    'common.delete': 'ሰርዝ',
    'common.edit': 'ኣርም',
    'common.view': 'ርአ',
    'common.back': 'ድሕሪት',
    'common.next': 'ቀጻሊ',
    'common.previous': 'ዝሓለፈ',
    'common.etb': 'ETB',
  },
};

// Additional keys (auth screen) kept in a separate map so every language stays
// in sync without editing four large objects.
const extraTranslations: Record<Language, Record<string, string>> = {
  en: {
    'auth.telegram': 'Continue with Telegram',
    'auth.telegramHint': 'Tap “Start” in the bot, then paste the 6-digit code it sends you.',
    'auth.verify': 'Verify',
    'auth.or': 'or',
    'auth.sendResetLink': 'Send reset link',
    'auth.sending': 'Sending...',
    'auth.checkEmail': 'Check your email',
    'auth.checkEmailVerification': 'We sent a verification link to',
    'auth.checkEmailReset': 'We sent a password reset link to',
    'auth.openOnDevice': 'Open it on this device to continue.',
    'auth.linkExpires': "The link expires in 1 hour. If you don't see the email, check spam or resend below.",
    'auth.resendLink': 'Resend link',
    'auth.linkResent': 'Link resent',
    'auth.tgPromoTitle': 'Get instant updates on Telegram',
    'auth.tgPromoDesc': 'Link our bot now and receive every order, delivery and wallet update straight to Telegram.',
    'auth.resetSent': 'We sent a reset link to your email',
    'auth.accountCreatedLink': 'Account created! Check your email for the verification link.',
    'auth.enterEmail': 'Please enter your email address',
    'auth.tgFailed': "Code invalid, expired, or this Telegram isn't linked to an account yet.",
    'auth.tgSignedIn': 'Signed in with Telegram',
  },
  am: {
    'auth.telegram': 'በቴሌግራም ይቀጥሉ',
    'auth.telegramHint': 'በቦቱ ውስጥ “Start” ይጫኑ፣ ከዚያ የተላከውን 6-አሃዝ ኮድ ያስገቡ።',
    'auth.verify': 'አረጋግጥ',
    'auth.or': 'ወይም',
    'auth.sendResetLink': 'የመቀየሪያ ሊንክ ላክ',
    'auth.sending': 'በመላክ ላይ...',
    'auth.checkEmail': 'ኢሜይልዎን ይመልከቱ',
    'auth.checkEmailVerification': 'የማረጋገጫ ሊንክ ልከናል ወደ',
    'auth.checkEmailReset': 'የይለፍ ቃል መቀየሪያ ሊንክ ልከናል ወደ',
    'auth.openOnDevice': 'ለመቀጠል በዚህ መሣሪያ ላይ ይክፈቱት።',
    'auth.linkExpires': 'ሊንኩ በ1 ሰዓት ያበቃል። ኢሜይሉን ካላዩ ስፓም ይመልከቱ ወይም እንደገና ይላኩ።',
    'auth.resendLink': 'ሊንክ እንደገና ላክ',
    'auth.linkResent': 'ሊንክ እንደገና ተልኳል',
    'auth.tgPromoTitle': 'በቴሌግራም ፈጣን መረጃ ያግኙ',
    'auth.tgPromoDesc': 'ቦታችንን አሁን ያገናኙ እና እያንዳንዱን የትዕዛዝ፣ የማድረስ እና የቦርሳ መረጃ በቴሌግራም ይቀበሉ።',
    'auth.resetSent': 'የመቀየሪያ ሊንክ ወደ ኢሜይልዎ ልከናል',
    'auth.accountCreatedLink': 'መለያ ተፈጥሯል! የማረጋገጫ ሊንክ በኢሜይልዎ ይመልከቱ።',
    'auth.enterEmail': 'እባክዎ ኢሜይል አድራሻዎን ያስገቡ',
    'auth.tgFailed': 'ኮዱ ልክ አይደለም፣ ጊዜው አልፎበታል ወይም ይህ ቴሌግራም ገና አልተገናኘም።',
    'auth.tgSignedIn': 'በቴሌግራም ገብተዋል',
  },
  om: {
    'auth.telegram': 'Telegram waliin itti fufi',
    'auth.telegramHint': 'Boota keessatti “Start” tuqi, sana booda koodii lakkoofsa 6 ergame galchi.',
    'auth.verify': 'Mirkaneessi',
    'auth.or': 'ykn',
    'auth.sendResetLink': 'Liinkii jijjiirraa ergi',
    'auth.sending': 'Ergaa jira...',
    'auth.checkEmail': 'Imeelii kee ilaali',
    'auth.checkEmailVerification': 'Liinkii mirkaneessaa erginee jirra gara',
    'auth.checkEmailReset': 'Liinkii jecha iccitii jijjiiruu erginee jirra gara',
    'auth.openOnDevice': 'Itti fufuuf meeshaa kana irratti bani.',
    'auth.linkExpires': "Liinkiin sa'aatii 1 keessatti ni xumurama. Yoo hin argine spam ilaali ykn irra deebi'ii ergi.",
    'auth.resendLink': "Liinkii irra deebi'ii ergi",
    'auth.linkResent': 'Liinkiin irra deebi’ee ergame',
    'auth.tgPromoTitle': 'Telegram irratti odeeffannoo battalaa argadhu',
    'auth.tgPromoDesc': 'Boota keenya amma walqunnamsiisi, odeeffannoo ajaja, geejjibaa fi boorsaa hunda Telegram irratti argadhu.',
    'auth.resetSent': 'Liinkii jijjiirraa imeelii keetti erginee jirra',
    'auth.accountCreatedLink': 'Akkaawuntiin uumameera! Liinkii mirkaneessaa imeelii kee keessaa ilaali.',
    'auth.enterEmail': 'Maaloo teessoo imeelii kee galchi',
    'auth.tgFailed': 'Koodichi sirrii miti, yeroon isaa darbeera, ykn Telegram kun hin walqunnamsiifamne.',
    'auth.tgSignedIn': 'Telegram waliin seentee jirta',
  },
  ti: {
    'auth.telegram': 'ብቴሌግራም ቀጽል',
    'auth.telegramHint': 'ኣብ ቦት “Start” ጠውቕ፣ ድሕሪኡ እቲ ዝተላእከ 6-ኣሃዝ ኮድ ኣእቱ።',
    'auth.verify': 'ኣረጋግጽ',
    'auth.or': 'ወይ',
    'auth.sendResetLink': 'መቐየሪ ሊንክ ስደድ',
    'auth.sending': 'ይለኣኽ ኣሎ...',
    'auth.checkEmail': 'ኢመይልካ ርአ',
    'auth.checkEmailVerification': 'መረጋገጺ ሊንክ ልኢኽናልካ ናብ',
    'auth.checkEmailReset': 'መቐየሪ ናይ መሕለፊ ቃል ሊንክ ልኢኽናልካ ናብ',
    'auth.openOnDevice': 'ንምቕጻል ኣብዚ መሳርሒ ክፈቶ።',
    'auth.linkExpires': 'እቲ ሊንክ ድሕሪ 1 ሰዓት የብቅዕ። እንተዘይረኺብካዮ ስፓም ርአ ወይ ደጊምካ ስደድ።',
    'auth.resendLink': 'ሊንክ ደጊምካ ስደድ',
    'auth.linkResent': 'ሊንክ ደጊሙ ተላኢኹ',
    'auth.tgPromoTitle': 'ኣብ ቴሌግራም ቅልጡፍ ሓበሬታ ርኸብ',
    'auth.tgPromoDesc': 'ሕጂ ቦትና ኣራኽብ፣ ኩሉ ናይ ትእዛዝ፣ ኣቕርቦትን ዋሌትን ሓበሬታ ብቴሌግራም ትቕበል።',
    'auth.resetSent': 'መቐየሪ ሊንክ ናብ ኢመይልካ ልኢኽናዮ',
    'auth.accountCreatedLink': 'ኣካውንት ተፈጢሩ! መረጋገጺ ሊንክ ኣብ ኢመይልካ ርአ።',
    'auth.enterEmail': 'በጃኻ ኢመይል ኣድራሻኻ ኣእቱ',
    'auth.tgFailed': 'እቲ ኮድ ቅኑዕ ኣይኮነን፣ ግዜኡ ሓሊፉ፣ ወይ እዚ ቴሌግራም ገና ኣይተኣሳሰረን።',
    'auth.tgSignedIn': 'ብቴሌግራም ኣቲኻ',
  },
};


const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  // Falls back to English when the active language is missing a key, so the
  // partially-translated languages (om, ti) still render correctly.
  const t = (key: string): string => {
    return (
      translations[language]?.[key] ||
      extraTranslations[language]?.[key] ||
      translations.en[key] ||
      extraTranslations.en[key] ||
      key
    );

  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
